### ISSUE TITLE
Searching for email within a Mailbox

### ISSUE THREAD

**Issue by malcolmwren** [nielsengelen/vbo365-rest#10]
Hi there
There seems to be a limit on the number of folders displayed in the drop down when looking at a mailbox.
what method does the search function use?

It appears to only search on those emails loaded onto the page using the "load more messages"

i am finding this area of the mailbox interrogation to be very limiting.

Should i be searching in a specific way?

**Comment by nielsengelen** [comment]
The search acts more as a filter based on what is visible on the page. I will change the text and add a help button to it in the next update as it is missleading now.

**Comment by nielsengelen** [comment]
Marked as change for next version/update.

**Comment by nielsengelen** [comment]
Implemented in version 3 of the portal (https://github.com/nielsengelen/vbo365-rest/releases/tag/v3.0).
