### ISSUE TITLE
php-cgi.exe causing high CPU spikes

### ISSUE THREAD

**Issue by Jombo01** [nielsengelen/vbo365-rest#100]
We are seeing lots of CPU spiking from the php-cgi.exe application in IIS.

We need to understand why this is happening. I understand that the issue isn't with IIS, but PHP.

VM is hosted in Azure with ample spec: SizeStandard D4 v3 vCPUs4 RAM16 GiB.

We have looked up 3 possible reasons this may be happening and these are:

Malformed PHP scripts
Large number of PHP processes
Problem in fetching content

Any assistance with this will be appreciated.

Best,

JJ

**Comment by nielsengelen** [comment]
Hi, seems I missed this issue. Are you still facing this issue and are you in need of assistance?
