### ISSUE TITLE
listing amount of mailboxes on landing page 

### ISSUE THREAD

**Issue by wavos** [nielsengelen/vbo365-rest#102]
Is there a way to increase the amount of mailboxes displayed on the tenants login page ?
I have a customer for example that is looking for a specific mailbox to restore, and the mailbox only appears when you select load more mailboxes.

Thanks in advance

**Comment by nielsengelen** [comment]
There is a global configuration in the config file ($limit) that will load 250 items for anything. If you want to change it specif for mailboxes only, you can adjust the veeam.class.php file at line 1181 (https://github.com/nielsengelen/vbo365-rest/blob/master/veeam.class.php#L1181).

**Comment by wavos** [comment]
Brilliant thanks Niels
