### ISSUE TITLE
Page reload in the restore step

### ISSUE THREAD

**Issue by Jugurtha13** [nielsengelen/vbo365-rest#11]
Hello,
First, thank you for the work done, the interface is very pleasant.
A quick question, when I select an email to restore, I select the "Original Location" option, the modal window (modalrestore original) opens well but I don't have time to fill in the login/password that the window (modal) closes itself.
I tested with Chrome (last version), Firefox (last version), IE (last version)

Thank you in advance for your help.

Regards,
Jugurtha

**Comment by Jugurtha13** [comment]
As additional information, this comes after a search item.
If I do "Load more message" to the desired email, the modal does not close.

**Comment by nielsengelen** [comment]
I will have to perform some testing to simulate this behaviour as it looks to happen randomly. Might be related to layers above eachother. Will report back with the fix once found. 

Thanks for reporting!

**Comment by Jugurtha13** [comment]
Great, thanks for your help.

**Comment by Jugurtha13** [comment]
I fixed the problem by replacing the bootstrap modal by the Swal2 library.

**Comment by nielsengelen** [comment]
Hi Jugurtha, I am not familiar with the Swal2 library (looks nice!) however the modal is coming from Semantic UI in the original code (not Bootstrap). Are you sure you replaced bootstrap? As I'm sure it will break the design if you remove Bootstrap. 

I will have to look into the Swal2 library and leverage this in the next major update and replace it. I am currently implementing some new features and resolving found bugs (like this one which happens very random to me in my environment).

**Comment by Jugurtha13** [comment]
Hello NielSengeln,

I developed a self-service portal for end users, they connect using their credential office365 (sso).
I encountered some problems with tenants having several domains but I bypassed the problem of getting the main domain tenant with the Microsoft Graph API library.

Indeed the interface is based on bootstrap4 but I also use Semantic-UI and I have no particular problem.

>I am currently implementing some new features and trying to resolve found bugs (like this one which happens very random to me in my environment).
Don't hesitate if I can help

**Comment by nielsengelen** [comment]
That sounds fantastic. I've been looking into the Graph API as well to combine it into enhanced self-service. Seems you beat me to it. Is it ok for you if I close this issue (since you've managed to resolve it for yourself)?

**Comment by Jugurtha13** [comment]
Yes, you can, thank you again. 
I look forward to seeing your next updates ;)

I have implemented multiselection and am currently trying to add the 3 states on the checkboxes, this will allow you to choose between keep and overwrite for each item.
This may be interesting to add in your next version.

For your information, there is a kb to install : https://www.veeam.com/kb2809  (maybe it will solve the problems you have)

Thanks again.

**Comment by nielsengelen** [comment]
Implemented Swal in favor of Semantic UI in version 3 of the portal (https://github.com/nielsengelen/vbo365-rest/releases/tag/v3.0).

Thank you again for sharing this gem!

**Comment by Jugurtha13** [comment]
With great pleasure.
I will try this new version to test the new features.

VBO365 has been upgraded to version 3, it will be an opportunity to test everything.
