### ISSUE TITLE
Datepickr problem after vbo365 2.0.0.814 upgrade

### ISSUE THREAD

**Issue by 52kards** [nielsengelen/vbo365-rest#12]
Hi, first and foremost - very nice portal, good job! We have been using it for a while now, and it have been working great. However, after we upgraded Veeam backup for Office 365 to version 20.0.0.814, datepickr is not working when tenants login (see the attached image). When you try to choose a date, the calender is stuck at "January 1970". I tried the portal in our test environment (vbo365 console with version .567) and it worked great. To verify that it was the upgrade that broke the portal, I upgraded the test vbo365 console to .814 also, and the same datepickr problem is present in the vbo web portal (test portal).

![datepickr_problem](https://user-images.githubusercontent.com/46590796/51020452-e1cecd80-157e-11e9-8bc1-29ebaead24c6.jpg)

**Comment by nielsengelen** [comment]
Thanks for reporting. Confirmed as a bug related to RESTful API call. I will update here as soon as I find a solution.

**Comment by nielsengelen** [comment]
The solution to this is to request the hotfix via Veeam support. Please open up a Veeam case and request the hotfix related to bug: 158283. Thanks!

**Comment by 52kards** [comment]
Thank you very much! That solved the issue.
