### ISSUE TITLE
The information returned is not correct in some cases.

### ISSUE THREAD

**Issue by Jugurtha13** [nielsengelen/vbo365-rest#13]
Hello,

It would just be necessary to correct this point for folder restores with content.
The application returns an error message when the restoration has worked well.

https://github.com/nielsengelen/vbo365-rest/blob/f3a51bcce8e5a4d6d96dd740bd667ab7638ed406/veeam.class.php#L1262

Replace with 
` if ($result['restoredItemsCount'] >= '1') { `

**Comment by nielsengelen** [comment]
Correct, thanks for the quick fix. Merged into the live code: https://github.com/nielsengelen/vbo365-rest/commit/76f1c7fa6baaeb900e4ac1b62973c1aa0143072c#diff-350cbfe0d02f67637da87a5869b89e79
