### ISSUE TITLE
Restore does not show any items and page is blank

### ISSUE THREAD

**Issue by MrGDW** [nielsengelen/vbo365-rest#15]
After we applied the Veeam private hotfix of issue #12 we could select a date again to start a restore.
But now we can see the mailboxes and sharepoint sites, but the main page doesn't show anything:

![screenshot_wad_549](https://user-images.githubusercontent.com/47847451/53153787-7a625f80-35b9-11e9-9db5-e729e3a6869f.png)

Does someone else have the same problem?

**Comment by Jugurtha13** [comment]
Hello MrGDW,

Two possibilities in my opinion:
1) You don't have any elements in your backup, the best way to know is to use the veeam explorer.
2) You have a timezone problem (conf php.ini) (check the value of the variable "pit" (javascript).

Nielsengelen will have the solution, certainly

**Comment by MrGDW** [comment]
Thanks for your suggestions.

Timezone is correct and there are also items when we do are restore directly with the Veeam Explorer.

Also the API keys are correct and shows up the documents and folders, when we put them into the swagger ui.

**Comment by MrGDW** [comment]
Ok, we found the problem.
the htaccess file is not working as expected. when I put manually the "uid" and "oid" then it works:

not working:
onedrive/f7b.../eb67...

working:
onedrive.php?oid=f7b...&uid=eb67...

**Comment by nielsengelen** [comment]
Correct, this portal uses htaccess. Make sure you enable it in your web service. Some examples on how to do this:
https://www.e2enetworks.com/help/knowledge-base/how-to-enable-mod_rewrite-on-apache-on-centos/

https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-debian-8

https://blogs.msdn.microsoft.com/azureossds/2015/04/23/converting-apache-htaccess-rules-to-iis-web-config-using-iis-manager-for-azure-websites/

**Comment by MrGDW** [comment]
ok, the problem was the "MulltiView" Option in Apache which was configured.
When we remove it, everything is working.
additional, if we add it to the htacces file, its also working:

# Disabable Apache MultiViews
Options -MultiViews

many thanks for your help!
