### ISSUE TITLE
Feature requests: Mailbox "filter by folder list" and folder restore

### ISSUE THREAD

**Issue by 52kards** [nielsengelen/vbo365-rest#16]
I see that people have requested full mailbox restore functionality, and was wondering if "folder restore" will be a part of that functionality?
 It would also be nice if the "Filter by folder" list could represent the hierarchy of the mailbox, and not list the folders alfabetically (with many folders in a big hierarchy it can maybe be a bit difficult to find the correct folder).

**Comment by nielsengelen** [comment]
I could add a search option to the "select folder" dropdown. Presenting them as the mailbox hierarchy is something on my todo list but I need to figure out the algorithm behind it.

In regards to restoring folders, that's a good request and I'll try to implement it in the next release (planning to have this in the next 2 months combined with the current VBO v3 BETA testing).

**Comment by 52kards** [comment]
Alright, sounds good. 

Good luck with development and testing.

**Comment by nielsengelen** [comment]
Marked as enhancement and feature request.
