### ISSUE TITLE
Cannot login due to expired certificate

### ISSUE THREAD

**Issue by charris-crs** [nielsengelen/vbo365-rest#18]
We have downloaded the OVA and created a VM from it.
The VM is configured and boots OK and we have been able to configure the home page

We cannot login as we get a certificate error.
The certificate issued by Veeam expired on 21/09/2018
![image](https://user-images.githubusercontent.com/48958425/55012381-437bd100-4fdf-11e9-9324-8b596e61df61.png)

Where can we find this certificate to remove it and replace it with a valid certificate?

Thanks

**Comment by nielsengelen** [comment]
Hi, 

This looks like the self-signed SSL certificate which was generated for the httpd service on the OVA has expired as it was only made for 1 year. You can either disable SSL or update it. It doesn't change much for the web application.

You can update it by running the following command (certificate will be 10 years):
```sudo openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt```

Then restart httpd:
```sudo systemctl restart httpd.service```

More info on this can be found in the following guide: https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-apache-for-centos-7

**Comment by charris-crs** [comment]
Hi Niels
just a quick thank you.
I now have the Portal working
Basically I have had to:
1) Set the Timezone to match the server
2) Edit veeam.class.php - login
3) Update the certificate
4) Check for rewrite module
5) Create .htaccess file to redirect exchange to exchange.php

Many Thanks for your help
Best regards

Clive

**Comment by nielsengelen** [comment]
Normally the .htaccess should work as it is but without deeper insight, it is a bit hard to tell what could be wrong. The timezone match is something I haven't seen before. 

Once I update the OVA, I will just leverage a certificate for 10 years, even though it is ment for demo purpose in it's current state.

Thanks for the update!

**Comment by charris-crs** [comment]
Hi Niels

I couldn’t find a file .htaccess in /var/www/html/ so had to create one.

Regards

Clive


Clive Harris
Managed Services Consultant
Covenco Recovery Services

Mobile: +44
Direct Dial: +44 (0)01295 274937
Fax: +44 (0)1753 732500
Email: clive.harris@covenco-dr.co.uk<mailto:clive.harris@covenco-dr.co.uk>


For more information about Covenco Recovery Services please visit our website at http://www.covenco-dr.co.uk<http://www.covenco-dr.co.uk/>
Follow us on: LinkedIn<mhtml:file://C:/Users/User/AppData/Roaming/Microsoft/Signatures/Clive%20Harris.mht!https://www.linkedin.com/company/1228295?trk=tyah&trkInfo=clickedVertical%3Acompany%2CentityType%3AentityHistoryName%2CclickedEntityId%3Acompany_1228295%2Cidx%3A0> | Twitter<mhtml:file://C:/Users/User/AppData/Roaming/Microsoft/Signatures/Clive%20Harris.mht!https://twitter.com/CovencoDR>

[819EC020]
     [85F1BB2E]   [60027F6C]

Company Registration Number: 3059168
Head Office Address:  Unit 4, MXL Centre, Lombard Way, Banbury, OX16 4TJ

This e-mail communication does not create or vary any contractual relationship between Covenco Recovery Services Limited (CRS) and you. Internet communications are not secure and accordingly CRS does not accept any legal liability for the contents of this message. The contents of this e-mail are confidential to the intended recipient at the e-mail address to which it has been addressed. It may not be disclosed to or used by anyone other than this addressee, nor may it be copied in any way. If received in error, please contact CRS on the above office number quoting the name of the sender and the addressee and then delete it from your system. Please note that neither CRS nor the sender accepts any responsibility for viruses and it is your responsibility to scan the e-mail and attachments (if any).

Registered Address: 5 South Parade, Summertown, Oxford, OX2 7JL, United Kingdom
