### ISSUE TITLE
Feature Request: Full mailbox restore

### ISSUE THREAD

**Issue by FlorianAlbeck** [nielsengelen/vbo365-rest#2]
With the Veeam Exchange Explorer it is possible to restore whole o365 mailboxes. 
As far as I see, this is not possible in the frontend. Only single item mail restore seems available.

Would it be possible to implement this?

**Comment by FlorianAlbeck** [comment]
Well... both! :) Follow up question: Where does the outlook need to be installed for .pst export? On the VBO/VBR server or on the client pc which is connecting to this frontend?

**Comment by nielsengelen** [comment]
You have to install this on the VBO server. As taken from the userguide:

> You must have a 64-bit version of Microsoft Outlook 2016, Microsoft Outlook 2013 or Microsoft Outlook 2010 installed on the computer running restore sessions.>

**Comment by nielsengelen** [comment]
Marked as change for next version/update.

**Comment by nielsengelen** [comment]
Implemented in version 3 of the portal (https://github.com/nielsengelen/vbo365-rest/releases/tag/v3.0).
