### ISSUE TITLE
Page not fount

### ISSUE THREAD

**Issue by dmontesdrp** [nielsengelen/vbo365-rest#20]
when i try to use the exchange restore page it sends me this error T### he requested URL /exchange/0b401a78-d9a4-48a0-8312-db13f3974d69 was not found on this server. any suggestion to repear it ?

**Comment by nielsengelen** [comment]
This looks like the rewrite rules aren’t working. Make sure you have enabled it as described in the readme file depending on the web server you are using underneath.

**Comment by dmontesdrp** [comment]
The rewrite is active, I'm using apache2 with ubuntu 16.4 but the error still

**Comment by dmontesdrp** [comment]
This is the .htaccess from the server 

<IfModule mod_rewrite.c>
SetEnv HTTP_MOD_REWRITE On

RewriteEngine On

# Rewrite rules
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^index/?$ index.php [NC,L]

# Exchange
RewriteRule ^exchange/?$ exchange.php [NC,L]
RewriteRule ^exchange/([^/]+)/?$ exchange.php?oid=$1 [L,QSA]
RewriteRule ^exchange/([^/]+)/([^/]+)/?$ exchange.php?oid=$1&uid=$2 [L,QSA]

# OneDrive
RewriteRule ^onedrive/?$ onedrive.php [NC,L]
RewriteRule ^onedrive/([^/]+)/?$ onedrive.php?oid=$1 [L,QSA]
RewriteRule ^onedrive/([^/]+)/([^/]+)/?$ onedrive.php?oid=$1&uid=$2 [L,QSA]

# SharePoint
RewriteRule ^sharepoint/?$ sharepoint.php [NC,L]
RewriteRule ^sharepoint/([^/]+)/?$ sharepoint.php?oid=$1 [L,QSA]
RewriteRule ^sharepoint/([^/]+)/([^/]+)/?$ sharepoint.php?oid=$1&sid=$2 [L,QSA]
RewriteRule ^sharepoint/([^/]+)/([^/]+)/([^/]+)/?$ sharepoint.php?oid=$1&sid=$2&cid=$3 [L,QSA]
RewriteRule ^sharepoint/([^/]+)/([^/]+)/([^/]+)/([^/]+)/?$ sharepoint.php?oid=$1&sid=$2&cid=$3&type=$4 [L,QSA]

# Disable directory browsing
Options -Indexes

Options +FollowSymLinks
</IfModule>

<FilesMatch "^\.">
Order allow,deny
Deny from all
</FilesMatch>

<Files readme.md>
Order allow,deny
Deny from all
</Files>

<Files LICENSE>
Order allow,deny
Deny from all
</Files>
~

**Comment by nielsengelen** [comment]
Could you confirm, after logging in, you can actually go to /exchange or /onedrive (via the top navigation bar)? The posted htaccess seems to be a bit off in the end (original and correct file is https://github.com/nielsengelen/vbo365-rest/blob/master/.htaccess)

**Comment by dmontesdrp** [comment]
it's stil not working 

I changed the htaccess 

![image](https://user-images.githubusercontent.com/49328259/55743489-0e687900-59f8-11e9-8a75-5e3c1ed40686.png)

**Comment by nielsengelen** [comment]
This means mod rewrite is not enabled on the apache webservice.
Please try the following:
`sudo a2enmod rewrite`
`sudo systemctl restart apache2`

Next is to edit the configuration file:
`sudo nano /etc/apache2/sites-available/000-default.conf`

There should be something like this:
`<VirtualHost *:80>
    <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>`

Make sure you have AllowOverride All or the htaccess won't work.

**Comment by dmontesdrp** [comment]
Let me show my virtual host configuration

<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        #ServerName www.example.com

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
  <Directory /var/www/html>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>

</VirtualHost>

The rewrite mode is enable 

![image](https://user-images.githubusercontent.com/49328259/55749484-a2414180-5a06-11e9-95b2-1d9bf2ab3050.png)

Actually this is the third server installation with all dependencies as you explained

**Comment by dmontesdrp** [comment]
I'll try again with a different OS like CENTOS, if I can't install it, i'll contact you

**Comment by nielsengelen** [comment]
It should work fine as I leverage Ubuntu as well. One of my next steps is to make an OVA download available in the upcoming weeks.

**Comment by dmontesdrp** [comment]
Do you have a complete installation manual over this product?.

I'm thinking in one fo the steps, Somenthing is missing when I made the installation.

**Comment by nielsengelen** [comment]
All the steps for the portal are in there. The only exception is the setup on the web servers as there are plenty of guides out there. I linked the ones I used for Apache and IIS and deployed multiple times. If the rewrite isn’t working it is related to your Apache config. You have to make sure AllowOverride is set to All for the root.

**Comment by dmontesdrp** [comment]
I resolved htaccess using centos and apache but it doesn't display exchange view jus only shows this 
![image](https://user-images.githubusercontent.com/49328259/56087052-eaa69800-5e28-11e9-8b6a-020df5ab12bb.png)

**Comment by nielsengelen** [comment]
If you select the organization on the left, you should see the options to start the restore. It looks ok on the screenshot.

**Comment by dmontesdrp** [comment]
When I select the organization name, it appears the seam page,it doesn't show the options

**Comment by nielsengelen** [comment]
I've been doing some testing with some new machines and it looks like "MultiViews" within the apache configuration is the issue.

Please edit the apache configuration file and change it to
```
<Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```
