### ISSUE TITLE
End-User Restore Option

### ISSUE THREAD

**Issue by marcohorstmann** [nielsengelen/vbo365-rest#21]
**Is your feature request related to a problem? Please describe.**
I talked to a customer recently and they told me that in his opinion this product doesn't work for him because his users should access or restore their own data themself.

**Describe the solution you'd like**
My idea is to provide a second authentication for this project. I tried this project from Microsoft (https://docs.microsoft.com/de-de/graph/tutorials/php) to authenticate against my O365 account.
With this session we are authenticated as user and now will be forwarded into his Restore Portal where he can restore his stuff by himself or browse and search his mailbox, etc..

**Comment by nielsengelen** [comment]
Hi Marco, thanks for the feature request. This has come up before and it something for the long run. For now, the main goal of the portal is to serve as an example for service providers.
