### ISSUE TITLE
Portal not working

### ISSUE THREAD

**Issue by cesadan01** [nielsengelen/vbo365-rest#22]
Hello,

I configured vbo on an IIS with PHP 7.3.5, but after logging in with an admin user, the console seems like no other option if I break.

![image](https://user-images.githubusercontent.com/50356087/57279336-1116c680-70a9-11e9-9325-25f5d5a08825.png)

The logout button does not work either.

What do you think can be?

The configuration seems correct

![image](https://user-images.githubusercontent.com/50356087/57279294-f3496180-70a8-11e9-8025-ff460ffdd66b.png)

![image](https://user-images.githubusercontent.com/50356087/57279315-052b0480-70a9-11e9-925c-a2266bda6a90.png)

Thanks a lot.

Daniele

**Comment by nielsengelen** [comment]
Hi Daniele, the design does look correct. Are you logging in via SERVER\user  or DOMAIN\user? There is currently a bug if you log in as admin in the form of admin@domain.com. 

You could check the RESTful API logs under 'C:\ProgramData\Veeam\Backup365\Logs' - look for the last file labeled Veeam.Archiver.REST_....log. It could help in finding an error or wrong call in there from where we can move forward.

**Comment by cesadan01** [comment]
Hi Nielsengelen,

thanks for your anwser, I use a local user that is in local Administrators group

[cid:image001.png@01D50580.25B55050]

I am attaching the log file, inside I see this error, but on the web I find nothing about it.

08/05/2019 09:20:53    6 (5616) Error: Method 'CreateSession' in type 'Veeam.Exchange.REST.Store.RestoreSessionAdmin' from assembly 'Veeam.Exchange.REST, Version=9.6.4.1078, Culture=neutral, PublicKeyToken=null' does not have an implementation.
08/05/2019 09:20:53    6 (5616) Type: System.TypeLoadException
08/05/2019 09:20:53    6 (5616) Stack:


Thanks again.

Best regards.



 
Quello che gli altri faranno domani...
Daniele Cesario
Senior System Engineer MSP
Via Lombardia, 2/A
20068  
Peschiera Borromeo MI
daniele.cesario@4ward.it
+39 02 99265811
+39 3357383366
www.4ward.it
Da: nielsengelen <notifications@github.com>
Inviato: martedì 7 maggio 2019 19:04
A: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
Cc: Daniele Cesario <daniele.cesario@4ward.it>; Author <author@noreply.github.com>
Oggetto: Re: [nielsengelen/vbo365-rest] Portal not working (#22)


Hi Daniele, the design does look correct. Are you logging in via SERVER\user or DOMAIN\user? There is currently a bug if you log in as admin in the form of admin@domain.com<mailto:admin@domain.com>.

You could check the RESTful API logs under 'C:\ProgramData\Veeam\Backup365\Logs' - look for the last file labeled Veeam.Archiver.REST_....log. It could help in finding an error or wrong call in there from where we can move forward.

**Comment by nielsengelen** [comment]
Hi Daniele,

I haven't seen that error, to be honest. I would suggest contacting Veeam support with this error/snippet. Maybe they have seen it already and have a fix for it. To me, it looks like something is wrong with the DLL from the Veeam Explorer for Exchange.

**Comment by cesadan01** [comment]
Okay, thank you.
I will follow your advice.

Have a nice day.



 
Quello che gli altri faranno domani...
Daniele Cesario
Senior System Engineer MSP
Via Lombardia, 2/A
20068  
Peschiera Borromeo MI
daniele.cesario@4ward.it
+39 02 99265811
+39 3357383366
www.4ward.it
Da: nielsengelen <notifications@github.com>
Inviato: mercoledì 8 maggio 2019 09:45
A: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
Cc: Daniele Cesario <daniele.cesario@4ward.it>; Author <author@noreply.github.com>
Oggetto: Re: [nielsengelen/vbo365-rest] Portal not working (#22)


Hi Daniele,

I haven't seen that error, to be honest. I would suggest contacting Veeam support with this error/snippet. Maybe they have seen it already and have a fix for it. To me, it looks like something is wrong with the DLL from the Veeam Explorer for Exchange.

**Comment by cesadan01** [comment]
Hi Nielsen,


I write to you, because after opening the ticket in Veeam their response was:

Hello Daniele,

Thank you for contacting Veeam Customer Technical Support.
My name is Peter, I am an engineer from Veeam Backup for Office 365 support team and I will be assisting you with this case.

Sorry if I am not getting you right, but as far as I know, there is no official  Self-Service Web Portal for Veeam Backup for Microsoft Office 365, only the one which was created by one of our users and published here:
http://foonet.be/2018/08/08/veeam-backup-for-microsoft-office-365-self-service-web-portal-release/

According to our support policy, we do not provide support for any customer scripts, therefore I am afraid I will not be able to assist you with this issue
https://www.veeam.com/veeam_software_support_policy_ds.pdf

I suggest you contact the person, who released that application as probably he has some fix for that issue.


At this point, can you help us out?

Thanks a lot.

Best regards.




 
Quello che gli altri faranno domani...
Daniele Cesario
Senior System Engineer MSP
Via Lombardia, 2/A
20068  
Peschiera Borromeo MI
daniele.cesario@4ward.it
+39 02 99265811
+39 3357383366
www.4ward.it
Da: nielsengelen <notifications@github.com>
Inviato: mercoledì 8 maggio 2019 11:03
A: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
Cc: Daniele Cesario <daniele.cesario@4ward.it>; Author <author@noreply.github.com>
Oggetto: Re: [nielsengelen/vbo365-rest] Portal not working (#22)


Closed #22<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnielsengelen%2Fvbo365-rest%2Fissues%2F22&data=02%7C01%7Cdaniele.cesario%404ward.it%7Cef5feee1e64c46fe52b608d6d3940524%7C389309be55ce414599da2d9e706bb4d9%7C0%7C0%7C636929030032262576&sdata=dDyrPKYMY4wwRe9UeY8ofpU4TlbjIPlOlFhfS7cmDUw%3D&reserved=0>.
