### ISSUE TITLE
Export Failed - 64-bit version of Microsoft Outlook 2010 or later is not installed.

### ISSUE THREAD

**Issue by paulhouselander** [nielsengelen/vbo365-rest#24]
**Describe the bug**
Not a bug but if I try an export to a PST I get the message

"Export Failed
64-bit version of Microsoft Outlook 2010 or later is not installed."

Does the server running VBO365 need Outlook installed? 

I am running the portal on a linux box does that make any difference?

Thanks

Paul

**Comment by nielsengelen** [comment]
Correct, as described in the [user guide](https://helpcenter.veeam.com/docs/backup/explorers/vex_data_export.html?ver=95u4) it is required to install Outlook on the VBO365 server to perform an export to PST. 

Running the portal on a Linux box doesn't make a difference (it is also the main source of development).
