### ISSUE TITLE
Authentication TImeout

### ISSUE THREAD

**Issue by charris-crs** [nielsengelen/vbo365-rest#27]
When entering username and password at Login screen the following is displayed
cURL error 28: Connection timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

The login request is sent and 10 seconds later fails
Is there anywhere to set a timeout or to increase the current 100000 milliseconds.

Suggestions from Websearching advise creating a CURL file, but I'm not sure where to do this and how to link it in.

We are using VBO365 version 3.0. Both the VBO server and the Portal Webserver have been rebooted.

Many Thanks

**Comment by nielsengelen** [comment]
By default, the time out is set to 30 seconds. This is defined in the veeam.class.php file at line 24 (            'connect_timeout' => 30,). Did you enable the RESTful API service on the VBO server and did u go over the setup.php file to configure the IP and port settings?

**Comment by charris-crs** [comment]
Hi Niels,

It the timeout is 30 secs why is it failing after 10 secs and reporting the same?

The Website comes up ok we only get the timeout trying to login

Thanks


Clive Harris
Managed Services Consultant
Covenco Recovery Services

Mobile: +44
Direct Dial: +44 (0)01295 274944
Email: clive.harris@covenco-dr.co.uk<mailto:clive.harris@covenco-dr.co.uk>


For more information about Covenco Recovery Services please visit our website at http://www.covenco-dr.co.uk<http://www.covenco-dr.co.uk/>
Follow us on: LinkedIn<mhtml:file://C:/Users/User/AppData/Roaming/Microsoft/Signatures/Clive%20Harris.mht!https://www.linkedin.com/company/1228295?trk=tyah&trkInfo=clickedVertical%3Acompany%2CentityType%3AentityHistoryName%2CclickedEntityId%3Acompany_1228295%2Cidx%3A0> | Twitter<mhtml:file://C:/Users/User/AppData/Roaming/Microsoft/Signatures/Clive%20Harris.mht!https://twitter.com/CovencoDR>

[819EC020]
     [85F1BB2E]   [60027F6C]

Company Registration Number: 3059168
Head Office Address:  Unit 4, MXL Centre, Lombard Way, Banbury, OX16 4TJ

This e-mail communication does not create or vary any contractual relationship between Covenco Recovery Services Limited (CRS) and you. Internet communications are not secure and accordingly CRS does not accept any legal liability for the contents of this message. The contents of this e-mail are confidential to the intended recipient at the e-mail address to which it has been addressed. It may not be disclosed to or used by anyone other than this addressee, nor may it be copied in any way. If received in error, please contact CRS on the above office number quoting the name of the sender and the addressee and then delete it from your system. Please note that neither CRS nor the sender accepts any responsibility for viruses and it is your responsibility to scan the e-mail and attachments (if any).

Registered Address: 5 South Parade, Summertown, Oxford, OX2 7JL, United Kingdom

**Comment by nielsengelen** [comment]
As said before, this usually means the web service can’t talk to the RESTful API service on the VBO server. Are you running the web portal on the same server or a seperate one?

Can u doublecheck the config.php file if it points to the correct IP and port? If there is a firewall, make sure the RESTful API service port is open and you can communicate with it. If the port is blocked, it is normal u received the 10 second time out error.

**Comment by charris-crs** [comment]
Hi Niels
All is now working -It was the IP address for the host was incorrect.
Many thanks for your help
