### ISSUE TITLE
count() Parameter must be an array or an object

### ISSUE THREAD

**Issue by Xilvaro** [nielsengelen/vbo365-rest#28]
Hi,

I'm getting the following error when clicking on every menu option (logged in as domain\administrator): 

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\includes\organizations.php on line 24

Also: When logged in al the counters stay at 0 (organisations, backup jobs, etc). 
In the REST log I can see I'm logged in and no further errors there. 

Logging in with a tenants credentials doesn't work at all at the moment. 
I'm running PHP 7.3.5.

Do you have any idea?

![image](https://user-images.githubusercontent.com/51399385/58940495-e12b1380-8779-11e9-8311-ba3ad674137f.png)

![image](https://user-images.githubusercontent.com/51399385/58940516-ee480280-8779-11e9-9ba8-5e88fd382c3f.png)

**Comment by nielsengelen** [comment]
From the looks of it, there is no organization added in the VBO console. Once you add an organization the warning will be gone as the total count will be 1 instead of 0 (which creates the message).

I will update it in the code however you can disable the warnings by opening the organizations.php file and by adding the following on line 2 (right after the <?php part):
error_reporting(0); // Disable all errors.

**Comment by Xilvaro** [comment]
Thanks, I will try that. 

The strange thing is, I've got about 5-10 organizations added in the console at the moment (and running backups) And I must add that the portal worked the first time around. Then after I hadn't used it for a month or 2 I got connection errors when logging in, this is when I installed the latest version of PHP/Apache and your code, and then this happened. 

So I'm not trying to suppress the message, but it seems that the webserver won't talk to VBO in a correct way or something. 

I already dug up some fix for Guzzle from Github regarding this issue, but that doesn't seem to fix it :(

https://github.com/guzzle/guzzle/pull/2038/files/f8265f45535e35e4fa5d4f7f3d3d916a82f802b7

**Comment by nielsengelen** [comment]
If you took the newer code, it could be due to the fact the config.php had a change (supports both v2 and v3). Can you double check the config.php file and make sure it points to the correct VBO server and API version?

**Comment by Xilvaro** [comment]
It connects to the FQDN of the portal, which on the Apache server resolves to 127.0.0.1, thats correct as the VBO instance is also running on this server. The port is correct and the API is set to V3 (my VBO version is 3.0.0.422

**Comment by nielsengelen** [comment]
If possible, we can do a remote session and dig into it - just drop me an e-mail via niels.engelen@veeam.com so we can arrange something. It all looks correct but the count() error means it fails at getting the organizations so the API call is returning incorrect info.

**Comment by Xilvaro** [comment]
Will do!
