### ISSUE TITLE
Curl error - Permission denied

### ISSUE THREAD

**Issue by bibawa** [nielsengelen/vbo365-rest#29]
HI,

I'm testing the VBO dashboard but when I try to logon I got error 'cURL error 7: Failed to connect to 192.168.100.200: Permission denied'..

I installed the Veeam 365 Console into a fresh server 2019 machine, and the vbo dashboard on a Linux server, from the VBO Dashboard server I can ping my veeam server and can as well reach the veeam rest api on port 4443.

Any idea ?

**Comment by nielsengelen** [comment]
If you get a permission denied (failed to connect), it usually means the Windows firewall is causing problems. How did you test the RESTful API service port check? Was this on the VBO server or was this from the server running the web portal?

**Comment by sergeygorlinsky** [comment]
I have problem "cURL error 7: Failed to connect to IP: Permission denied (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) "

The problem occurs when logging in to PORTAL. RESTful API is ON, port is available.

**Comment by nielsengelen** [comment]
As mentioned in my previous post, this would be a firewall issue. Are you trying this from a remote server? Could you give some more details about the server gisting the portal. Did you also update the config file to connect to the right IP (or ran setup)?

**Comment by rdjong80** [comment]
Hi Niels, i am having same problem ( curl error 7 failed to connect to ip : permission denied.)

all firewalls ( both on vbo dashboard server and windows servers disabled..
i can telnet from vbs dashboard server to port 4443 and successfull establish connection.

i try to login into the web portal with admin credentials of my windows domain. however i get the error above.
any ideas on what could go wrong ?

**Comment by nielsengelen** [comment]
Could you give some more information on the server running the portal? Is this a Linux server? If so, could it be SElinux is active? This could be the issue.

**Comment by rdjong80** [comment]
Hi Niels, I already solved the issue. Propably port 4443 was already in use on my windows server, I changed the API port to 4444 and modified the config. Php.

Everything worked fine after that.

________________________________
