### ISSUE TITLE
Feature Request: Disable Admin Login

### ISSUE THREAD

**Issue by FlorianAlbeck** [nielsengelen/vbo365-rest#3]
Since I dont want to have a REST API frontend in a DMZ which is open to everyone and therefore a possible attack vector, is it possible to disable any admin login, so that only tenants / o365 accounts can login?

**Comment by nielsengelen** [comment]
Marked as change for next version/update.

**Comment by nielsengelen** [comment]
Implemented in version 3 of the portal (https://github.com/nielsengelen/vbo365-rest/releases/tag/v3.0).
