### ISSUE TITLE
OneDrive/SharePoint restore issues

### ISSUE THREAD

**Issue by Neelon** [nielsengelen/vbo365-rest#30]
I'm having trouble restoring OneDrive and SharePoint throught the web portal. Clicking 'Start Restore' or 'Explore last backup' pops up the window saying the Restore Session Started, but then the web portal goes quiet (continues loading untill it times out). However, on the VBO365 server I can see a restore session running. So it has started the restore session, but does not want to return anything from the call.

Restore for Exchange does not have these issues, thinking it might be something wrong with the Explorers themself. However, normal restore with all Explorers through VBO365 console works fine.

I have tried hosting the web portal on both IIS and Apache. 
Tried hosting the web portal in a different subnet, and on the VBO365 server itself.
Also tried opening all ports between the web server and VBO365 server, when hosted in a different subnet.
Both SSL and self-signed certificate has been tested.
Restore as admin or organization service account makes no difference.

VBO365 server is hosted on the same server as Cloud Connect.
VBO365 jobs are split into three: one job for Exchange and Archive, one for OneDrive and one for SharePoint (could this be the culprit somehow?)

One other thing I have noticed is that API calls running to list the organizations and licensing are very slow to return any result, and also time out sometimes.

Would really appriciate any help I can get, if you have the time.

Harald

**Comment by nielsengelen** [comment]
This could be a resource problem. Could you test the Veeam Explorers from the console and 'time' how long it takes for them to open and mount the data for OneDrive and SharePoint?

Could you also give some more information on the resources provides for the servers (mostly CPU/memory)?

**Comment by Neelon** [comment]
For Exchange it takes max 10 seconds, SharePoint takes ~50 seconds and OneDrive takes ~30 seconds. This is when I right-click All Organizations (3 in total) and choose to explore latest available backup. I figure this is the correct way, since the Rest API also starts Explorers with all Organization in it.

Starting Explorer for Exchange/SharePoint/OneDrive for only a single organization is fast, ~10 seconds.

Specs:
VBO365-/Cloud Connect server - 10 cores (2.2 GHz), 48 GB RAM
VBO365 Proxy/Repo - 8 cores (2.2 GHz), 24 GB RAM
Web server - 2 cores (2.2 GHz), 4 GB RAM

Top two running Windows Server 2019, while web server runs Ubuntu server 18.04

**Comment by nielsengelen** [comment]
It is advised to increase or disable the PHP maximum execution time limit. This can be modified in the php.ini file as described per [changing the maximum execution time limit](https://www.simplified.guide/php/increase-max-execution-time). By default, this is set to 30 seconds and then the PHP process is ended. As a result, the web browser doesn't get any response and you get the timeout. 

Can you try this and let me know if it works better?

**Comment by Neelon** [comment]
Changing the max_execution_limit to 0 made it work.. kind of. It takes a long time before the restore session shows up in the web portal. After some testing, it could seem like the larger the organization (by users) the more time it takes. OneDrive restore for the smallest organization (~100 users) took 8 minutes, 12 minutes for an organization with ~300 users and I gave up waiting after 35 minutes for an organization with ~700 users.
SharePoint restore follows the same pattern.
In terms of storage size, the organzation with 100 users use far more than the organization with 200 users. 

Any clue what could cause this?

**Comment by nielsengelen** [comment]
After starting the restore via the API, it waits for the Explorers to start in the background to process the sessions. 

In regards to the performance, I would advise to contact the official Veeam support and see if they can improve your setup as this is related to VBO and maybe the connectivity to O365. There isn't much I can do on this aspect. As you've noticed, the portal works but the slow part is related to the VBO server.

**Comment by Neelon** [comment]
Is there some way to determine exactly which API calls the web application sends towards the VBO365 server? I need to recreate the calls made for exploring/mounting a restore point done from the web app, and send them from another tool for troubleshooting.

**Comment by nielsengelen** [comment]
All the API calls performed are in the file called [veeam.class.php](https://github.com/nielsengelen/vbo365-rest/blob/master/veeam.class.php) - they are labeled in a readable way:
- getJobs
- getOrganization
