### ISSUE TITLE
restorte pst file status

### ISSUE THREAD

**Issue by marcovader** [nielsengelen/vbo365-rest#31]
**Is your feature request related to a problem? Please describe.**
When you restore a pst file, a status is not shown. If a user tries to download a second time the same pst during the first restore job (because he thinks noting is happening) performance issues can occur.

**Describe the solution you'd like**
A pst restore status bar

**Describe alternatives you've considered**
Mention this in the user manual that there is no status view

**Additional context**
N/A

**Comment by nielsengelen** [comment]
Hi Marco, thanks for the request. I've had this request before but haven't implemented this. For now, the fastest temporary solution I can provide is to add a popup/message stating the export is in process. 

Tracking the export in a progress bar is a different story as the RESTful API service doesn't return the percentage at which it is at during the export.

**Comment by marcovader** [comment]
Hi Niels,

A pop-up would be a very use full feature


Met vriendelijke groet,

Marco Vader
Product Manager

[cid:image001.png@01D5460C.FA578810]<https://www.previder.com/nl?utm_source=outlook-handtekening&utm_medium=email&utm_content=actie-afbeelding&utm_campaign=een-eitje-25-03-2019>
Expolaan 50 | 7556 BE Hengelo | Nederland
T (088) 332 33 33
M 06 41246110
E m.vader@previder.nl
I www.previder.com/nl<https://www.previder.com/nl?utm_source=outlook-handtekening&utm_medium=email&utm_content=actie-afbeelding&utm_campaign=een-eitje-25-03-2019>

[cid:image002.png@01D526A9.0F4905B0]<https://www.previder.com/nl/Werken-Bij/Consultants?utm_campaign=werken-bij-10-05-2019&utm_medium=email&utm_source=outlook-handtekening>

Altijd het laatste Previder nieuws in je inbox? Meld je aan voor de nieuwsbrief!<https://www.previder.com/nl/contact/nieuwsbrief?utm_source=outlook-handtekening&utm_medium=email&utm_content=actie-afbeelding&utm_campaign=een-eitje-25-03-2019>

[cid:image003.png@01D5460C.FA578810]<https://twitter.com/previder>  [cid:image004.png@01D5460C.FA578810] <https://www.facebook.com/previder>   [cid:image005.png@01D5460C.FA578810] <https://www.linkedin.com/company/previder>   [cid:image006.png@01D5460C.FA578810] <https://www.youtube.com/c/previder>


Van: nielsengelen [mailto:notifications@github.com]
Verzonden: maandag 29 juli 2019 12:02
Aan: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
CC: Marco Vader <m.vader@previder.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [nielsengelen/vbo365-rest] restorte pst file status (#31)


Hi Marco, thanks for the request. I've had this request before but haven't implemented this. For now, the fastest temporary solution I can provide is to add a popup/message stating the export is in process.

Tracking the export in a progress bar is a different story as the RESTful API service doesn't return the percentage at which it is at during the export.
