### ISSUE TITLE
pst after restore not offered as download

### ISSUE THREAD

**Issue by marcovader** [nielsengelen/vbo365-rest#32]
**Describe the bug**
When a larger pst file is restored as a download it is not offered as a downloadable file. Smaller pst files are offered as a download.

**To Reproduce**
1. download pst

**Expected behavior**
After download offered as a download

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 10 1809
- Browser: Google-Chrome Chrome
- Version: 75.0.3770.142 (64-bits)

**Comment by nielsengelen** [comment]
Hi Marco, this is most likely due to the export process for the large mailbox still running in the background and a time-out happening. Do you have some more information on the size of the large mailbox?

**Comment by marcovader** [comment]
Hi Niels,

I asked the engineer who's tested this but he's on his summer holiday for 3 weeks.

tbc.

Regards,

Marco

**Comment by nielsengelen** [comment]
Hi Marco, any update on this?

**Comment by marcovader** [comment]
Hi Niels,

I aksed the engineer forn an update. I let you know asap.

Regards,

Marco

**Comment by nielsengelen** [comment]
Closing this as it is a known issue with large exports. Next version of the portal will show a popup saying the export is running and put the timeout to 0 assuring it should offer the download.
