### ISSUE TITLE
pst download folder deleted 

### ISSUE THREAD

**Issue by marcovader** [nielsengelen/vbo365-rest#33]
**Describe the bug**
After starting job 2, restore job folder 1 incl. pst file is deleted. See images.

**To Reproduce**
Start  2 differten pst download jobs simultanious.

**Expected behavior**
download job 1 must not be deleted

**Screenshots**
See images

**Desktop (please complete the following information):**
- OS: Windows 10 1809
- Browser: Google-Chrome Chrome
- Version: 75.0.3770.142 (64-bits)

![pst download job 1](https://user-images.githubusercontent.com/51906962/62035893-09227a80-b1f1-11e9-9ee2-cbb018ab4d86.png)
![pst download job 2](https://user-images.githubusercontent.com/51906962/62035903-0cb60180-b1f1-11e9-9c7a-03e03bc11407.png)

**Smartphone (please complete the following information):**
N/A

**Comment by nielsengelen** [comment]
Hi Marco, the PST temp folder will always be deleted. This is not something I can control as this is how VBO365 works via the RESTful service. Am I correct in understanding that the goal for you is to save every export (as this may cause your TEMP folder to fill up your OS disk)?

**Comment by marcovader** [comment]
Hi Niels,

I asked the engineer who's tested this but he's on his summer holiday for 3 weeks.

tbc.

Regards,

Marco

**Comment by nielsengelen** [comment]
Hi Marco, any update on this?

**Comment by marcovader** [comment]
Hi Niels,

I aksed the engineer forn an update. I let you know asap.

Regards,

Marco

**Comment by nielsengelen** [comment]
Marco, I would suggest posting this on the [Veeam Forums](https://forums.veeam.com/veeam-backup-for-microsoft-office-365-f48/) as a feature request to allow to save exports.
