### ISSUE TITLE
Unable to download large mailbox PST files

### ISSUE THREAD

**Issue by mdali313** [nielsengelen/vbo365-rest#34]
**Describe the bug**

When I download the large mailboxes (15GB) as PST file it's redirecting to "hostanme/download.php" blank page and nothing happen after that.  But the restore session still running on the VBO server and PST file downloading to the VBO server temp directory.

**Comment by nielsengelen** [comment]
This is a known issue of the portal when exporting large accounts (mailbox/onedrive/site). This is on my todo to find a workaround but so far the only solution I could think of would be to run the export process in the background, store the file somewhere and create a sort of 'download basket'.
