### ISSUE TITLE
Exploring SharePoint backups

### ISSUE THREAD

**Issue by Neelon** [nielsengelen/vbo365-rest#36]
When exploring a SharePoint backup, files and folders beyond "Site->Documents->General" are not responding to actions. A folder in "General" won't open, and both files and folders in the "General" won't respond to restore options (Download plain file/zip, restore to original location).

Browsing the same files and folders in Veeam Explorer for SharePoint, for the same restore point, works as it should.

Do you have an idea what could cause this?

**Comment by nielsengelen** [comment]
What happens when you open the folder? Do you get a white page or does the page just keeps loading/spinning?

**Comment by Neelon** [comment]
Neither. The folders have a clickable link, but there is nothing happening when trying to open the folder (or clicking the 'Restore to original location' from the drop-down menu).
Also, files in the same folder behave the same. Restore actions does not trigger anything.
Tested with both Chrome and Firefox, in case of a browser issue, and no difference there.

**Comment by nielsengelen** [comment]
@Neelon any chance we can have a remote call on this since this is difficult for me to debug via GitHub. Please drop me an e-mail via niels.engelen@veeam.com so we can look at this issue.

**Comment by nielsengelen** [comment]
Following up via mail. Closing this issue for now.

**Comment by nielsengelen** [comment]
Resolved in 4.1 release (https://github.com/nielsengelen/vbo365-rest/releases/tag/v4.1).
