### ISSUE TITLE
cURL error 4: OpenSSL was built without SSLv3 support

### ISSUE THREAD

**Issue by heroes1412** [nielsengelen/vbo365-rest#37]
**Describe the bug**
i install your source with latest xampp for windows, but i cannot login and get bellow message:
cURL error 4: OpenSSL was built without SSLv3 support

**Comment by nielsengelen** [comment]
Could you tell me which xampp version you have? I would need to test this to find a solution.

**Comment by heroes1412** [comment]
im using latest xampp version (7.3.12)

**Comment by nielsengelen** [comment]
I've tried this version as well (AMPP for Windows 7.3.12) and it works out of the box. Could be there is something wrong with your installation. Could you maybe re-install it and try again?

**Comment by roseflowerdaria** [comment]
hi
how to Curl error: OpenSSL was built without SSLv3 support browser
