### ISSUE TITLE
Support for modern authentication

### ISSUE THREAD

**Issue by kristofpoppe** [nielsengelen/vbo365-rest#38]
Hi Niels,

Really appreciating you're updating this project with every new version of VBO. Small question regarding the self-service aspect. How do you cope with tenants which are using modern authentication ? You could delegate access to a tenant 'admin' which then can perform restores, check for his/her company, but when using MA don't think this will work.

**Comment by nielsengelen** [comment]
Hi Kristof,

Not sure what you mean exactly. If a tenant is added via MFA, you can leverage the username & password to log in.
