### ISSUE TITLE
cURL error 7: Failed to connect 

### ISSUE THREAD

**Issue by kfir1200** [nielsengelen/vbo365-rest#39]
I'm getting this error when I'm trying to connect :

URL error 7: Failed to connect to XXX.XXX.XX.XX port 4443: Timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html).

the port is opened I've check it but i still getting this error.

I'm using IIS and windows server 2016 and PHP version 7.3.

**Comment by nielsengelen** [comment]
Are you running the portal on the same server or is this a standalone? The message means it gets a timeout to the specific IP so this is related to a networking issue.

**Comment by kfir1200** [comment]
Yes, the portal is on the same server.

**Comment by nielsengelen** [comment]
Are you sure the RESTful API service is running on port 4443? You can double check this via the Services console (running services.msc). It looks like it isn't running and therefor you get a timeout.

**Comment by kfir1200** [comment]
I can't see the RESTful API service on the services console, i need to install the service manually ?

**Comment by nielsengelen** [comment]
Did you modify the veeam.class.php by any chance? By default, the portal ignores self-signed certifcates to make it work.

**Comment by kfir1200** [comment]
Hi Niels,

Yes, i' ve changed it because it's written in the first page:

"Note: There is currently no SSL verification due to self signed certificate testing, please change settings 'verify' to true or remove the specific line accordingly in veeam.class.php."

I will download the file again and check if it solved my problem.

**Comment by nielsengelen** [comment]
If you don't use a valid SSL certificate within Veeam Backup for Microsoft Office 365", you should use the default file and leave "verify" to false.

**Comment by kfir1200** [comment]
Hi Niels,

It's working now, thank you.

but i want to know please how i can add more companies in the web portal ?

i only see two of them and i have much more.

Thanks again Niels.

**Comment by nielsengelen** [comment]
If you add the specific organization to the VBO console, they will also show up in the web portal. We just read the data from the API which gives back what is added in the VBO console.

**Comment by kfir1200** [comment]
Hi Niels,

Thank you and have a good weekend.
