### ISSUE TITLE
Unable to login as tenant

### ISSUE THREAD

**Issue by lharmer** [nielsengelen/vbo365-rest#4]
When logging in as a tenant, I get _The username or password provided is incorrect. Make sure you are logging in with your Office 365 account._

Administrator login works perfectly.

The tenant credentials are definitely correct, and using them in the Veeam Explorer for Exchange work ok.
Is there any diagnostic logging that can be enabled?

**Comment by nielsengelen** [comment]
A tenant is an organization which has been added so you will need to use the same login and it should work. If you add admin@domain.onmicrosoft.com as the organization you will need to login with that account as well. It is not possible to login with user@domain.onmicrosoft.com (only the main login works).

**Comment by lharmer** [comment]
Thanks, this is with the admin account for the organization I was trying.
I have attempted admin@domain.onmicrosoft.com, and reset the job in VBO365 to use the onmicrosoft.com username as well.

Also tested another dummy organization with admin@domain.onmicrosoft.com from scratch, and still get the same error I'm afraid.

**Comment by nielsengelen** [comment]
I would suggest looking in the RESTful logs which can be found under C:\ProgramData\Veeam\Backup365\Logs (file looks like Veeam.Archiver.REST_2018_07_24_15_50_33.log). Try to login, open the file and check the error you are getting. It should explain what goes wrong.

**Comment by lharmer** [comment]
Thanks managed to track it down from the log - we did not have the explorer for Exchange/Sharepoint installed on the VBO365 machine, installed and all working! Cheers.
