### ISSUE TITLE
Get the index.php to show without web.config, but it doesnt work.

### ISSUE THREAD

**Issue by Lundte** [nielsengelen/vbo365-rest#42]
**Describe the bug**
When the web.config file is there i get this error: 
Configuration file '\\?\C:\inetpub\wwwroot\web.config' does not contain a root <configuration> tag

When I rename the Web.config file so it wont be used. The login page will be shown but I get this error when I try to login: 
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

1. Go to http://localhost/index.php with the web.config file
2. Go to http://localhost/index.php without the web.config file
3. try to login without the web.config file

**Desktop (please complete the following information):**
 - OS: Windows server 2016 
 - Browser chrome
 - Version IIS 10 and PHP 7.3

**Comment by Lundte** [comment]
**UPDATE**

So I figured out was what wrong with the web.config file for IIS/Windows. 

Have pasted the missing part:

<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                            """ The veeam rules"""
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

But but but... It still doesnt work.. Now i hit this issue: 
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

Can you help please?

**Comment by nielsengelen** [comment]
Which cURL version are you using?

**Comment by Lundte** [comment]
The default from PHP 7.3.7

**Comment by nielsengelen** [comment]
cURL error 35 usually means the package has issues due to version mismatch of cURL and SSL, outdated cURL package or firewall restrictions. 

Could you tell me the output of curl -V (in a cmd window)? Also, do you have a firewall active on the server?

**Comment by Lundte** [comment]
Hi.

I thought that IIS would install curl by it self.. But nope. It only own the curl dll, which you can enable but have no function.. 

So.. I have installed curl version 7.46.0 now, and now the error is gone. But now I get this error: 
curl error 7 failed to connect to 127.0.0.1 port 4443: Connection refused

**Comment by Lundte** [comment]
Hi.

I thought that IIS would install curl by it self.. But nope. It only own the curl dll, which you can enable but have no function..

So.. I have installed curl version 7.46.0 now. I'm still getting this error: 
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

**Comment by Lundte** [comment]
Any suggest?

**Comment by nielsengelen** [comment]
I will have to do some testing myself to see what may cause this as this is a new error to me.

**Comment by Lundte** [comment]
Okay, I wait :) 
Hopefully you will find something usefull.

**Comment by Lundte** [comment]
Have you tried it yet? :)

**Comment by nielsengelen** [comment]
Finally managed to proper testing but I haven't been able to reproduce this issue in any way. From the looks of it, it is related to OpenSSL not accepting the certificate due to security issues. Can u try to perform a curl against your RESTful API service and see if that works from the server running the portal?
