### ISSUE TITLE
Upgrade towards v4 

### ISSUE THREAD

**Issue by marcovader** [nielsengelen/vbo365-rest#43]
Hi Niels,

We upgraded our VEEAM Office backup 365 towards v4.0. Is it manditory to upgrade also your VBO365 towards V4? We do experience without the upgrade errors during mail restores. See attchment.

![thumbnail_image001](https://user-images.githubusercontent.com/51906962/72067689-ad056b80-32e3-11ea-9de3-592a883aea29.png)
![thumbnail_image002](https://user-images.githubusercontent.com/51906962/72067710-bb538780-32e3-11ea-94c5-66a41514c327.png)

Regards,

Marco

**Comment by nielsengelen** [comment]
Marco, a new version was released along with VBO v4 so it may be good to download it and replace the files (or code) that have changed (depending on if u did customization or not). The errors you are seeing are related due to API changes in v4 and they have been added in the portal update.

**Comment by marcovader** [comment]
Thanks! We will update.
