### ISSUE TITLE
Unable to login as tenant

### ISSUE THREAD

**Issue by dustin2050** [nielsengelen/vbo365-rest#44]
When logging in as a tenant, I get "Authorization Error: Invalid credential"
Administrator login works perfectly.

i already checked the RESTful logs (C:\ProgramData\Veeam\Backup365\Logs) without any information about Errors with Logins or similar..

**Comment by nielsengelen** [comment]
Did you enable authentication for tenants as mentioned in the [https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40](user guide).

**Comment by dustin2050** [comment]
Yes i did...

**Comment by nielsengelen** [comment]
Just to be sure, you can only log in with the account you used to add the organization to VBO (the admin account). If you try to log in with another account (user@domain.com for example), it won't work as this is not supported.

**Comment by dustin2050** [comment]
yes, im trying to login with the credentials which i configured for the Backup Job/Organization :/

**Comment by dustin2050** [comment]
now its working! after restarting the VBO Server everything works like expected! ;)
Thank you for your help!

**Comment by netscaper71** [comment]
Hello, we have the same. After some time password for MS account was changed and update of VBO server performed. Now we cannot login as tenant, but can login as admins. REST service is up and running, VBO server was restarted, logs are empty about reasons. VBO is 4.0.1.545

**Comment by nielsengelen** [comment]
@netscaper71 did you just change the password for the MS account or did u change the authentication method used?

**Comment by netscaper71** [comment]
Hi. Changed password. Authentication method left the same. After getting the error the organization was added once again and result is the same. Local admin or domain admin is able to login, but organization (o365) admin no.

**Comment by nielsengelen** [comment]
If the login fails, it should be shown in the logs what the reason is. Did you already check the RESTful API logs?

**Comment by netscaper71** [comment]
in the log is missing related information about this one failed log in. Successful logins are recorded this on is not.

**Comment by nielsengelen** [comment]
Could you send me a copy of the logs via niels.engelen@veeam.com so I can analyze them and we can follow it up via there?
