### ISSUE TITLE
Veeam 365 mailbox .pst download never start

### ISSUE THREAD

**Issue by dimitrismitk** [nielsengelen/vbo365-rest#46]
Hello,

When trying to export a whole mailbox (not just some emails) from the WEB GUI the “Your export is starting” window is displayed and after ~60” i am redirected to the download.php page.
After that the download never starts.
Even if the restore job in Veeam 365 management console finished the export in C:\Windows\Temp\REST_EXPORT_7a6bab70, the download never starts.

Could i ask if there is any known issue about this process or i am missing something?

Thanks,
Dimitris

**Comment by nielsengelen** [comment]
Do you have an idea of the size? Most likely you hit the PHP timeout issue. Large downloads is something complex via the UI and most likely will require another way of processing.

**Comment by carokiel** [comment]
Would it be an idea to run the export in a background task and provide a download link on the portal, when finished?

**Comment by nielsengelen** [comment]
It is something I've been considering implementing but haven't managed to create yet. The concern around it is that you need either space on the portal server to store it during the export process or provide something like AWS S3 or Azure Blob. 

Space on the server could be an issue for large exports (someone asked me to export a 400GB OneDrive), AWS S3/Azure Blob would work there but that comes with an additional cost.
