### ISSUE TITLE
"Explore Last Backup" not visible for Tenants

### ISSUE THREAD

**Issue by carokiel** [nielsengelen/vbo365-rest#47]
Hi Niels,
first of all, thank you for the great work, you did here!
But I've found a few issues, I'm struggling with.
Here's the first:
When logging in as admin, I see a button "Explore Last Backup" after selecting an organization.
When logging in as a tenant, This button is not visible. So I need to specify a data (and a time) in order to browse the backups. This is quite unconveniant and I'd like to provide tenants the button "Explore last backup".
Since every tenant is 1:1 mapped to an O365-Org, I assume, this should be possible.

Can you point me in the right direction in enabling this button for tenants?

All the best from the Berlin area,
Caroline

**Comment by nielsengelen** [comment]
Hi Caroline,

Correct, this button is not available since there is a difference in possibilities from the VBO RESTful API. As an admin, it is easier to show the latest restore point and have the button. A tenant can't use that API call however I will look for a workaround and add the button. I will keep you posted with the outcome.

**Comment by carokiel** [comment]
Hi Niels,
thank you very much.

**Comment by carokiel** [comment]
Hi Niels,
do you already have an idea here?

/c

**Comment by nielsengelen** [comment]
Not yet but I will try to have this checked this week.

**Comment by nielsengelen** [comment]
I have just published an update to the 3 files in a new commit: https://github.com/nielsengelen/vbo365-rest/commit/14e359725a2c74a8d2dc21f85e2b8318629e4eac 

You can download the specific files (exchange.php, onedrive.php & sharepoint.php) and replace them in your current portal.

This should add the explore last backup and use the same design as the admin view. 

Let me know if something doesn't work.

**Comment by carokiel** [comment]
As of now, everything seems fine. We'll do some more testing and update here.

**Comment by carokiel** [comment]
The buttons works as expected. Thank you.
