### ISSUE TITLE
Exploring SharePoint subfolders not working (similar to Issue #36)

### ISSUE THREAD

**Issue by carokiel** [nielsengelen/vbo365-rest#48]
Hi Niels,
A customer has a SharePoint site containing a folder "Dokumente" with a folder "Rechnungen". Inside this folder, they archive invoices in .xls and .pdf format.
When using the web console, I can see the folder Dokumente and open it, so I see the folder "Rechnungen". "Rechnungen" is displayed as a link and hovering it, I can see a long link with GUIDs.
Wohever, I "cannot click" on the link. In detail, I can click, but nothing happens at all.
When using the Veeam Explorer for Sharepoint on the VBO, I can see the content.
The amount of files in the folder is pretty small (<50 items), so I don't expect any performance issues here.

Any idea on how to fix this?
If you need a remote session, just drop me a line, we can arrange this easily.

Best regards,
Caroline

**Comment by nielsengelen** [comment]
Hi Caroline, I am aware of this and I have been working on a solution for this. I should have a fix for it soon and will let you know once done.

**Comment by carokiel** [comment]
Hi Niels,
thank you very much for the quick update. Looking forward for the fix.

**Comment by nielsengelen** [comment]
Small update on this. As this wasn't as easy as I thought to fix, it will most likely be an update to the whole SharePoint page and takes some more time for troubleshooting and performing propers tests.

**Comment by carokiel** [comment]
Okay, will just wait for an update, then.
Thank you for your work.

**Comment by nielsengelen** [comment]
Resolved due to new design in 4.1 release (https://github.com/nielsengelen/vbo365-rest/releases/tag/v4.1).
