### ISSUE TITLE
Can't download PST from exchange or ZIP from onedrive backup

### ISSUE THREAD

**Issue by eazy** [nielsengelen/vbo365-rest#49]
Hi,

if I try to download a PST out of a exchnage Backup it just opens the /download.php in the browser and shows a white site. Same with onedrive while trying to download it as zip.

apache errorlog
`[Thu Apr 30 16:21:12.670990 2020] [php7:warn] [pid 6562] [client 123.123.123.123:58150] PHP Warning:  stream_get_contents(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 80, referer: https://portal.testsrv.de/exchange
[Thu Apr 30 16:29:02.089068 2020] [php7:warn] [pid 30062] [client 123.123.123.123:58996] PHP Warning:  fseek(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 203, referer: https://portal.testsrv.de/exchange
[Thu Apr 30 16:29:02.089747 2020] [php7:warn] [pid 30062] [client 123.123.123.123:58996] PHP Warning:  stream_get_contents(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 80, referer: https://portal.testsrv.de/exchange
[Thu Apr 30 16:36:36.037656 2020] [php7:warn] [pid 6570] [client 123.123.123.123:59939] PHP Warning:  fseek(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 203, referer: https://portal.testsrv.de/exchange
[Thu Apr 30 16:36:36.038173 2020] [php7:warn] [pid 6570] [client 123.123.123.123:59939] PHP Warning:  stream_get_contents(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 80, referer: https://portal.testsrv.de/exchange
[Thu Apr 30 16:41:11.349433 2020] [php7:warn] [pid 6574] [client 123.123.123.123:60442] PHP Warning:  fseek(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 203, referer: https://portal.testsrv.de/onedrive
[Thu Apr 30 16:41:11.349467 2020] [php7:warn] [pid 6574] [client 123.123.123.123:60442] PHP Warning:  stream_get_contents(): supplied resource is not a valid stream resource in /var/www/portal.testsrv.de/vendor/guzzlehttp/psr7/src/Stream.php on line 80, referer: https://portal.testsrv.de/onedrive`

In the RESTAPI Log of the Veeam Server everything looks good 
[log.txt](https://github.com/nielsengelen/vbo365-rest/files/4564227/log.txt)

Running on Debian buster with Apache and PHP 7.3.14-1 the latest version from https://github.com/nielsengelen/vbo365-rest
Veeam Backup for Microsoft OFfice 365 4.0.0.2516

While testing I'm logged in as a Tenant with the o365 admin credentials.

Thanks

**Comment by nielsengelen** [comment]
Could you tell me a bit more about the size of the PST (or the mailbox) that you are trying to download? It could be this is too large and a time-out happens.

**Comment by eazy** [comment]
sure, the onedrive has only a txt file with 4k.
Thanks!

**Comment by nielsengelen** [comment]
It could be related to a PHP timeout settings which gives this a white file. Downloads are a bit of a complex part of the portal but should work fine for smaller files. Did you try modifying the timeout as explained in https://www.simplified.guide/php/increase-max-execution-time ?

**Comment by eazy** [comment]
yes, max_execution_time ist set to 600 and verified in phpinfo.

The time from the click on download to the error in the log is only about 5 seconds.

OK, I'll have a deeper look and report. Thanks so far,

**Comment by eazy** [comment]
Ok, sorry problem solved. The DMZ Firewall has dropped the connection.
