### ISSUE TITLE
Trouble reviewing licenses

### ISSUE THREAD

**Issue by carokiel** [nielsengelen/vbo365-rest#50]
When I login as an admin, I can see the entire dashboard, which is fine (by the way, why can't see customers "their" dashboard?
But when I click on "Licenses", I get lots of lines like this one:
Notice: Undefined index: email in /var/www/html/includes/licensing.php on line 68
Below that, the used licenses are displayed, but where does this error come from?

Best regards,
Caroline

**Comment by nielsengelen** [comment]
Which VBO version are you running? This is one of the table entries normally but it looks like it isn't picked up correctly via the API.

**Comment by nielsengelen** [comment]
I will check if I can simulate the error and let you know.

**Comment by nielsengelen** [comment]
Found what is causing the issue but will need some time to find the fix. Will let you know once I published updated code.

Thanks for reporting.

**Comment by carokiel** [comment]
That's good news, thank you.

**Comment by nielsengelen** [comment]
I've published an update file to resolve this. This seems to happen if data is in multiple databases and the info is empty. For now the quick fix is to hide the email.
