### ISSUE TITLE
Cannot login to web portal, error - StreamHandler.php [line] 324 

### ISSUE THREAD

**Issue by netscaper71** [nielsengelen/vbo365-rest#51]
Hello, we are done installation  as in description and getting error - Error creating resource: [message] fopen(): SSL: Connection reset by peer [file] /var/www/vbo365-rest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 324 [message] fopen(): Failed to enable crypto [file] /var/www/vbo365-rest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 324 [message] fopen....

we are using self signed certificates, please share knowledge. We are using VBO 4.0.0.2516

**Comment by netscaper71** [comment]
after downgrade of php from 7.3 to 5.6 is working, but still we have some problems:

cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xx.xx.xx.xx:4443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by netscaper71** [comment]
was missing some packages I will add a comment later today with list.

**Comment by nielsengelen** [comment]
It would be great if you could list them so I can update the readme file with this. Thanks!

**Comment by netscaper71** [comment]
Working config on Debian10
apt-get update
apt-get upgrade
apt-get install vim gnupg2 curl
sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
curl -s https://packages.sury.org/php/apt.gpg | apt-key add -
apt-get update
apt-get install php5.6-cli php5.6-zip git unzip apache2 libapache2-mod-php5.6 apt-transport-https
a2enmod php5.6
a2enmod rewrite
curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar /usr/local/bin/composer
cd /var/www/
git clone https://github.com/nielsengelen/vbo365-rest.git
cd /var/www/vbo365-rest/
composer install
chown www-data:www-data -R /var/www
vim /etc/apache2/sites-enabled/000-default.conf
replace: 
DocumentRoot /var/www/html > /var/www/vbo365-rest
vim /etc/apache2/apache2.conf
add:
<Directory /var/www/vbo365-rest/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
apt-get dist-upgrade
service apache2 restart

**Comment by nielsengelen** [comment]
Thanks for sharing. I will add a sort of install file for debian 10 based on this. Is it ok if I close the issue as you managed to resolve it?

**Comment by netscaper71** [comment]
> Thanks for sharing. I will add a sort of install file for debian 10 based on this. Is it ok if I close the issue as you managed to resolve it?

yes, thank You for that great example of usage of REST api of Veeam o365 backup

**Comment by EmanuelKoena** [comment]
Good day

I need help with login on the self service portal for office 365, im getting the below error, cURL error 7: Failed to connect to 127.0.0.1:4443; Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html.

For some reason all ports were allowed but still I cannot login with my AD or admin account

**Comment by nielsengelen** [comment]
@EmanuelKoena  Can u verify the RESTful API service is running? The error is quite self explaining saying connection refused which means it is either a firewall issue or the service is not running.

**Comment by EmanuelKoena** [comment]
Hi Niel

I can see the login screen but my credentials are not working.
Firewall is disabled and how do you check RESTful API service Where my portal is running.

[cid:image002.jpg@01D64EF7.36B1D100]

**Comment by nielsengelen** [comment]
You can check this within VBO365: https://helpcenter.veeam.com/docs/vbo365/guide/vbo_rest_api_settings.html?ver=40

Or run "services.msc" and check in the list if the service is running.

**Comment by EmanuelKoena** [comment]
The services are up and running

[cid:image002.jpg@01D64EF8.C1DBED00]

**Comment by nielsengelen** [comment]
Are you running the portal on the VBO server or is this on a standalone machine? If it is running on a standalone machine, you need to update 'config.php' and change the IP to match the IP for your VBO server.

**Comment by EmanuelKoena** [comment]
Hi Niel

Do you do remote sessions to try and help me resolve this issue

Thanks

**Comment by EmanuelKoena** [comment]
Hi Niel

Please advise if a remote session is possible tomorrow or you don’t do remote support.

Thanks

From: Emanuel Koena
Sent: Tuesday, June 30, 2020 4:17 PM
To: nielsengelen/vbo365-rest <reply@reply.github.com>; nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [nielsengelen/vbo365-rest] Cannot login to web portal, error - StreamHandler.php [line] 324 (#51)

Hi Niel

Do you do remote sessions to try and help me resolve this issue

Thanks

**Comment by nielsengelen** [comment]
Hi Emanuel, can u let me know if you are running the portal on the VBO server or is this on a standalone machine? This may be the main issue so a remote session is not needed if it is.

**Comment by EmanuelKoena** [comment]
Morning

Im running the portal on a linux VM and the VBO server is a windows server.

Thanks

On Jul 3, 2020 8:43 AM, nielsengelen <notifications@github.com> wrote:

Hi Emanuel, can u let me know if you are running the portal on the VBO server or is this on a standalone machine? This may be the main issue so a remote session is not needed if it is.

**Comment by nielsengelen** [comment]
As suggested, you need to update 'config.php' and change the IP to match the IP for your VBO server. Right now the portal tries to connect to 127.0.0.1 which is not the VBO server.

**Comment by EmanuelKoena** [comment]
Hi Niel

I can confirm that the VBO server is standalone server.

Please see below configs from the php file.

[cid:image002.jpg@01D659CA.77028CD0]

Thanks

**Comment by nielsengelen** [comment]
@EmanuelKoena the image isn't working sadly, could you try again or drop me an e-mail via niels.engelen@veeam.com so we can follow it up via there?
