### ISSUE TITLE
Searching for emails

### ISSUE THREAD

**Issue by KLESYS** [nielsengelen/vbo365-rest#52]
Hi Niels,

is it possible to add a search function to the portal? It would be great to be able to search for a specific mail.

**Comment by nielsengelen** [comment]
I'll note it down as a feature request. Which items would you search for? From a user, to a specific user, mail subject,... If you could provide me a list that would help as there are quite some parameters available.

**Comment by KLESYS** [comment]
Thank you! It would be great to have that feature in a future version.
I think the most important items to search for would be:
From (a user)
To (a specfic user)
CC
Mail subject
Date/ Time (sent and received)
