### ISSUE TITLE
Exploring Sharepoint Folders immediately shows "session expired"

### ISSUE THREAD

**Issue by carokiel** [nielsengelen/vbo365-rest#53]
Used browsers: Edge (last stable version) / Chrome 81.0

This is, what we do:
- log on to the portal
- Click on "Sharepoint"
- Click on "Explore last Backup"
- Click on "Photos" in the left frame:
![1](https://user-images.githubusercontent.com/63641185/81946373-92c7fb00-95ff-11ea-8ba3-8eff9a4f7d90.png)
Immediately after clicking on "Photos", the following error message is shown:
![2](https://user-images.githubusercontent.com/63641185/81946531-c2770300-95ff-11ea-9d85-bbfca0a23d5e.png)

Can you assist us here?
Thank you,
Caroline

**Comment by nielsengelen** [comment]
Hi Caroline,

I'll have to attempt to simulate this as I don't see this when I use a tenant login on my demo environments. I will get back to you once I know more.

**Comment by carokiel** [comment]
Hi Niels,

shall we make a remote session, so I can demonstrate it to you and give you access to the entire system?

 

/Caroline

  _____  


Caroline Kiel

PingUs Solutions


CEO

 



Tel.:
Fax:
Mobil:
E-Mail: 

 <tel:+49%2033056%20401-111> +49 33056 401-111
 <tel:+49%2033056%20401-190> +49 33056 401-190
 <tel:+49%20172%203232%20800> +49 172 3232 800
 <mailto:Caroline.Kiel@pingus.de> Caroline.Kiel@pingus.de


Marienstr. 1a
D-16552 Mühlenbecker Land
Ortsteil Schildow
 <https://www.pingus.de> https://www.pingus.de 

	
  _____  


PingUs Solutions GmbH & Co. KG


Geschäftsführung (Managing Partners)

Anja Kiel, Caroline Kiel


Steuernummer (Tax ID)

053/161/09049


UID-Nr. (VAT-No.)

DE 813 720 069


Amtsgericht (County Court)

Neuruppin HRA 1440 OPR

  _____  

Important Note:
This e-mail may contain trade secrets or privileged, undisclosed or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal. Thank you for your cooperation. 
. 

 <https://docks.pingus.de/> 

Von: nielsengelen <notifications@github.com> 
Gesendet: Freitag, 15. Mai 2020 11:37
An: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
Cc: Caroline Kiel <Caroline.Kiel@pingus.de>; Author <author@noreply.github.com>
Betreff: [Ext] Re: [nielsengelen/vbo365-rest] Exploring Sharepoint Folders immediately shows "session expired" (#53)

 

Hi Caroline,

I'll have to attempt to simulate this as I don't see this when I use a tenant login on my demo environments. I will get back to you once I know more.

**Comment by nielsengelen** [comment]
I will drop you an e-mail and let's see what is causing this behavior.

**Comment by nielsengelen** [comment]
Marked as enhancement and bug in the portal to be resolved in a next update.

**Comment by Kaveerp** [comment]
Hi Nielsengelen

Thank you the fantastic Portal, please advise if you have solved the issue for "Session Expired".
I recieve this issue everytime I open a SharePoint Subsite
![Error](https://user-images.githubusercontent.com/67784894/86459395-009ec200-bd27-11ea-8060-53502f18cc81.PNG)

Kind Regards
