### ISSUE TITLE
Need help with setup

### ISSUE THREAD

**Issue by RenAToSRL** [nielsengelen/vbo365-rest#54]
Hello, I am currently trying to test this project. I already have the web server set up with apache. (I can reach the login screen). 

It is not clear to me how to login into the portal, is it with O365 admin credentials? IP and password for the VBO365 VM? Something i need to configure from the REST configuration on Veeams side?

Thanks in advance, and sorry if this isn't the right place to ask.

**Comment by nielsengelen** [comment]
Hi, there are 2 options to set up the portal.
1) You open the config.php file and manually edit the settings to point to your VBO365 server
2) You browse to the setup.php file where you can configure your VBO365 settings via a form (remember to remove the setup.php file later on)

On the VBO365 side, you will have to configure the [RESTful API settings](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_rest_api_settings.html?ver=40) and the [authentication settings](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40).

**Comment by OliverMarkKLESYS** [comment]
Hi, if you try to login with an Office365 Admin with MFA enabled (i hope you have enabled it), you need an App-Password for the Account.

[Microsoft Help for App Passwords with MFA](https://docs.microsoft.com/de-de/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords)

**Comment by RenAToSRL** [comment]
Hello, we have done some advancements, mainly related to the connection within both servers. We are still having problems getting the portal to be updated according to the config file. Our config file has all the data in it, yet our portal still has the default name, and can´t connect to our vbo server.
We could not get to setup.php through the browser either, even if we see the file on our VM.

**Comment by nielsengelen** [comment]
If it still shows the defaults, it means the config file is not updated or being loaded from the folder. Do you have a screencap of how it looks like?

**Comment by RenAToSRL** [comment]
View from centos VM:
![image](https://user-images.githubusercontent.com/65736921/87794224-b59fa700-c81c-11ea-8b53-c76427d5a4de.png)

Our config file (edited manually):
![image](https://user-images.githubusercontent.com/65736921/87794304-cbad6780-c81c-11ea-8141-fd572ce7470f.png)

What we get when trying to edit the file from setup.php:
![image](https://user-images.githubusercontent.com/65736921/87794381-eaabf980-c81c-11ea-9c37-2f2522db2735.png)

How our portal looks like right now:
![image](https://user-images.githubusercontent.com/65736921/87794430-fd263300-c81c-11ea-8cf6-5cbcbea86b2b.png)

Thanks in advance for your help!

**Comment by nielsengelen** [comment]
If you already edited the config file, you don’t need to run the setup anymore. You should be able to log in to the portal by using either an O365 credential (as used to add an organisation to VBO365) or a Windows administrator account.

**Comment by RenAToSRL** [comment]
We´ve tried login from O365 credential and Windows administrator, to no avail. We get the error: cURL error 7: Failed to connect to 172.19.100.76: Permission denied

Since the portal´s title is “Login” and the site´s name “Veeam Backup for Microsoft Office 365”, and we don´t see the name we specified in the config file anywhere, I am assuming it´s not reading it as it should.

De: nielsengelen <notifications@github.com>
Enviado el: viernes, 17 de julio de 2020 11:34
Para: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
CC: Renato Zurita <rzurita@at.com.uy>; Author <author@noreply.github.com>
Asunto: Re: [nielsengelen/vbo365-rest] Need help with setup (#54)


If you already edited the config file, you don’t need to run the setup anymore. You should be able to log in to the portal by using either an O365 credential (as used to add an organisation to VBO365) or a Windows administrator account.

**Comment by nielsengelen** [comment]
I notice the file you edit is in /root/vbo365-rest. This looks like the wrong file. Normally apache hosts websites within /var/www/html. Can u check if the file is in there?

**Comment by RenAToSRL** [comment]
Hello there,

We´ve redeployed the server, and could get the portal to work.
We have only been able to log in with the windows server credentials, from there we can´t do certain things, like starting a restore session.

We haven´t been able to log in with our microsoft 365 organization credentials, any considerations for this?

**Comment by nielsengelen** [comment]
Can you confirm you enabled [authentication settings](https://helpcenter.veeam.com/docs/vbo365/guide/vbo_authentication_settings.html?ver=40)? Are you using the new MFA by any chance which uses an application?

**Comment by RenAToSRL** [comment]
Yes, we have them enabled, with a self signed certificate. This account is not using MFA, just a regular password

**Comment by nielsengelen** [comment]
Could you send me a copy of your RESTful API logs (found under C:\ProgramData\Veeam\Backup365\Logs) via mail (niels.engelen@veeam.com)? I will need to analyze those to help you further.

**Comment by KLESYS** [comment]
@RenAToSRL try an App Password for the Admin User
[Manage app passwords for two-step verification
](https://docs.microsoft.com/de-de/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords#:~:text=So%20erstellen%20Sie%20App%2DKennw%C3%B6rter%20im%20Office%20365%2DPortal&text=Sign%20in%20to%20Office%20365,Seite%20App%2DKennw%C3%B6rter%20zu%20%C3%B6ffnen.)

**Comment by RenAToSRL** [comment]
@nielsengelen I´ve sent you the logs via Wetransfer

@KLESYS Would that help in any way other than security?

**Comment by nielsengelen** [comment]
That would not solve the o365 login issue but just increase security. And right now, the new MFA is not supported yet in this portal project.

**Comment by nielsengelen** [comment]
@RenAToSRL can u confirm you have installed both the Explorers? It looks like there is something wrong with them.

**Comment by RenAToSRL** [comment]
Hello Niels. we updated our web portal to the latest release, and we checked our explorers, there was indeed a compatibility problem between our explorers version and our VBO365 install.

We've since removed and reinstalled the explorers, and we are able to restore correctly (From our Veeam for office365 console).
From our web portal, we still can´t perform any kind of restore, although we can see on the exchange tab that our backups are being recognized correctly.
![image](https://user-images.githubusercontent.com/65736921/91881785-6d1b3c00-ec58-11ea-9223-375be0d50dde.png)

Furthermore, we still can´t access our webportal through O365 Admin credentials, but we can access with the VBO365 VM´s local administrator password. (we are not using double factor on the O365 acc, so that should not be an issue).

To add to this, we can only see our Exchange backups on the portal, our Sharepoint tab returns "No Sharepoint sites found for this organization" (We do have a sharepoint site backed up, and can browse it from Veeam explorer.)

Thanks for your help.

**Comment by RenAToSRL** [comment]
I´m attaching screencaps of the state of our **Authentication** and **REST API** tabs on Veeam´s side, in case you see anything of relevance.

![image](https://user-images.githubusercontent.com/65736921/91882917-10b91c00-ec5a-11ea-8c12-eab95db51c15.png)
![image](https://user-images.githubusercontent.com/65736921/91882940-17479380-ec5a-11ea-8b25-c7be2a8a63f8.png)

**Comment by nielsengelen** [comment]
@RenAToSRL at this point in time, I suggest arranging a remote call since this will be hard to troubleshoot via GitHub. Can you drop me an e-mail via niels.engelen@veeam.com so we can arrange it?
