### ISSUE TITLE
cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by jackyku** [nielsengelen/vbo365-rest#55]
i hit this error when login. May i know what is this related?

**Comment by nielsengelen** [comment]
It looks like the error isn’t complete. Can you paste the error in a comment? Did you modify the config file to connect to your VBO365 server correctly?

**Comment by jackyku** [comment]
cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

the error is get when i login and have set the config. 

![image](https://user-images.githubusercontent.com/16839497/83043161-190b2500-a075-11ea-96e8-f27fba9b8ae7.png)
========================================
[root@localhost ~]# cat /var/www/html/config.php
<?php
$host = '192.168.2.155'; /* Veeam Backup for Microsoft Office 365 server (hostname or IP) */
$port = '4443'; /* RESTful API service port (default: 4443) */
$title = 'Veeam Backup for Microsoft Office 365'; /* Custom title for the portal to be displayed in the browser title */
$version = 'v4'; /* RESTful API version (default: v4) */
$administrator = 'yes'; /* Allow Windows administrator accounts to be used as a login (yes or no) */
?>
================================================

**Comment by nielsengelen** [comment]
Error 7 means it couldn't connect, could it be you have a firewall running on the VBO365 server (make sure port 4443 is open.
