### ISSUE TITLE
Error loading OneDrive backups

### ISSUE THREAD

**Issue by pzaf** [nielsengelen/vbo365-rest#56]
Hello, I have fairly large OneDrive backup that will not load and receive the following error:
_Error creating resource: [message] fopen (https://<my-uri>:443/v4/RestoreSessions/<sessionID>/Organization/OneDrives?offset=0&limit=1000): failed to open stream: HTTP request failed! [file] /var/www/sites/vbo365-rest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line]323_

The backup loads with no issues when using the Veeam Explorer.
I have another organization backup that I can test with (however much smaller in size) and it works with no issues.

**Comment by nielsengelen** [comment]
How large is the specific organization in terms of users?

**Comment by pzaf** [comment]
In terms of users - 595

**Comment by pzaf** [comment]
Hi Neils, do you have any updates?

**Comment by nielsengelen** [comment]
Hi, did u modify the PHP timeout value already? It is advised to increase or disable the PHP maximum execution time limit. This can be modified in the php.ini file as described per [changing the maximum execution time limit](https://www.simplified.guide/php/increase-max-execution-time). I think this will solve the timeout while loading. 

Another option is to lower the '1000' in the code but then I need to add something to load the next amount of accounts.

**Comment by pzaf** [comment]
Hi Niels, yes the mac_execution_time is set to 300. Should I increase this timeout further?

**Comment by nielsengelen** [comment]
Can u put it to 0 as a test? That means 'unlimited' time. Just to figure out if it is related to PHP or not.

**Comment by pzaf** [comment]
yes I can do that. I will get back to you with the results early next week.

**Comment by nielsengelen** [comment]
@pzaf any update?

**Comment by pzaf** [comment]
Hi Niels,
Unfortunately changing that max_execution_time to 0 did not fix the problem. The same error still occurs.

**Comment by pzaf** [comment]
@nielsengelen have you had a chance to investigate this issue further?

**Comment by nielsengelen** [comment]
Not yet. We may need to plan a remote call to see what goes wrong exactly. I will have an update later this week.

**Comment by nielsengelen** [comment]
@pzaf any chance we can follow this up via mail (niels.engelen@veeam.com) as I may need some logs.

**Comment by nielsengelen** [comment]
Follow up via mail ongoing.
