### ISSUE TITLE
VBO 4.0.1.531 supported?

### ISSUE THREAD

**Issue by miguelfna** [nielsengelen/vbo365-rest#57]
Hi is the VBO 4.0.1.531 supported?

When access the portal I',m getting this behaviour:

<a href="https://ibb.co/F5dGxW4"><img src="https://i.ibb.co/ZBbyLJz/o365ssportal-issue.png" alt="o365ssportal-issue" border="0"></a>

OS: ubuntu Server 18.04 LTS
Browser: Firefox, Chrome, Edge...

Also, for some reason I'm not able to login with the Organizations credentials (already permited in the configurations using a valid certificate).

Thanks in advance

Pedro

**Comment by nielsengelen** [comment]
I have not tested the latest update yet. The screenshot looks like a design issue because CSS isn't loading somethings correctly. Which login error do you get?

**Comment by miguelfna** [comment]
> 
> 
> I have not tested the latest update yet. The screenshot looks like a design issue because CSS isn't loading somethings correctly. Which login error do you get?

Hi, I was able to finally login with the organization credentials (replace the certificate with a self signedm then replaced again with the public one, and it worked...) 

I've have tried with a older VBO version, and the design issue i showing allways, any idea how to solve this ?

thanks

Pedro

**Comment by nielsengelen** [comment]
Are you 100% sure you did the composer command correct (composer install)? This should resolve all the CSS issues and load all the required components.

**Comment by miguelfna** [comment]
> 
> 
> Are you 100% sure you did the composer command correct (composer install)? This should resolve all the CSS issues and load all the required components.

Can I run it again ?

**Comment by nielsengelen** [comment]
Yes, you can run it again - it will update things if needed. After that, make sure you do a hard refresh in your browser.

**Comment by miguelfna** [comment]
> 
> 
> Yes, you can run it again - it will update things if needed. After that, make sure you do a hard refresh in your browser.

awsome, that worked like a charm, the only thing I need to do was delete the composer.lock file

Thanks

**Comment by nielsengelen** [comment]
Great, that sounds like a previous run got stuck and therefore it went wrong.
