### ISSUE TITLE
Multi Factor Authentication

### ISSUE THREAD

**Issue by charris-crs** [nielsengelen/vbo365-rest#59]
Hi Niels
A customer has just activated MFA using the "legacy" option.
VBO365 v4c is working ok with :
Application ID 
Application Secret: 
Application Password:  Note this is not the Username password
Username:

When trying to access the Web Portal there is an error invalid credentials using username and password

The portal is latest version on Ubuntu 18.04 with a Valid CA Certificate and works for other customers

Is there anything I need to change in the setup to get MFA to work?

Many Thanks
Clive

**Comment by nielsengelen** [comment]
U should be able to use the email address used and the application password in this case however I would need to check and verify this myself as I haven't set this up yet.

**Comment by charris-crs** [comment]
Hi Niels
i have tried the Username and username password but no joy.
i have also tried username and Application password but no joy.

Thanks

Clive

**Comment by nielsengelen** [comment]
I will have to do some testing. I think if u check the RESTful API logs, you may find some more information.

**Comment by charris-crs** [comment]
Hi Niels
there are no references to logon in the logs.
I tried to logon at 17:15 - last entry in the logs is 16:58.
Is there somewhere to increase the logging level

Thanks

**Comment by nielsengelen** [comment]
You can do this via the ribbon -> Help and Support -> Support information.

**Comment by charris-crs** [comment]
Hello Niels - with extended login I am seeing:
For Customer with Basic Authentication
02/07/2020 12:01:46    4 (23992)   Service started
02/07/2020 12:02:33   14 (22412) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
02/07/2020 12:02:33   19 (26172) Validating certificate chain...
02/07/2020 12:02:33   19 (26172) Certificate chain validation successfully completed.
02/07/2020 12:02:33   19 (26172) Validating certificate claims...
02/07/2020 12:02:33   19 (26172) Certificate claims:
02/07/2020 12:02:33   19 (26172)   Veeam Software
02/07/2020 12:02:33   19 (26172) Validation failed. Certificate is not valid for host 127.0.0.1
02/07/2020 12:02:33   14 (22412)   Successfully connected
02/07/2020 12:02:35   19 (26172) Request: GET https://ip_address:4443/v4/Organization
02/07/2020 12:02:35   19 (26172) Action started: Get organization (API version: V4)

For MFA Customer
02/07/2020 12:04:22    4 (15352)   Service started
02/07/2020 12:04:45   14 (25500) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
02/07/2020 12:04:45   19 (26516) Validating certificate chain...
02/07/2020 12:04:45   19 (26516) Certificate chain validation successfully completed.
02/07/2020 12:04:45   19 (26516) Validating certificate claims...
02/07/2020 12:04:45   19 (26516) Certificate claims:
02/07/2020 12:04:45   19 (26516)   Veeam Software
02/07/2020 12:04:45   19 (26516) Validation failed. Certificate is not valid for host 127.0.0.1
02/07/2020 12:04:45   14 (25500)   Connection failed
02/07/2020 12:04:45   14 (25500) Error: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
02/07/2020 12:04:45   14 (25500) Type: System.ServiceModel.Security.MessageSecurityException
02/07/2020 12:04:45   14 (25500) Stack:
02/07/2020 12:04:45   14 (25500) 
Server stack trace: 
   at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at System.ServiceModel.Channels.CommunicationObject.EndOpen(IAsyncResult result)

Exception rethrown at [0]: 
   at Veeam.Engine.Wcf.PrimitiveServiceClient`1.Open(CancellationToken token)
   at Veeam.Archiver.Integration.ArchiverConnector`2.CreateArchiverConnection(TE events, ICertificateValidator certificateValidator, IServiceConnectionConfig connectionConfig, Nullable`1 cancellationToken)
02/07/2020 12:04:45   14 (25500) Error: The server has rejected the client credentials.

Is this Certificate error of any consequence?

**Comment by nielsengelen** [comment]
Could you drop me an e-mail (niels.engelen@veeam.com) around this so we can do some troubleshooting to find the cause?

**Comment by nielsengelen** [comment]
Published in release v4.2.
