### ISSUE TITLE
Can't reach exchange or onedrive page

### ISSUE THREAD

**Issue by PleXi00** [nielsengelen/vbo365-rest#6]
hello,

thanks for your project. i can access index and basique admin information but i cannot access Exchange or onedrive pages.
http://localhost/exchange doesn't exist, i can force it with http://localhost/exchange.php but then i click on my organization on the left and it doesn't exist either
![image](https://user-images.githubusercontent.com/3042143/45021794-c719a480-b032-11e8-9d67-a13d6439bf23.png)
Any idea ?

using IIS with PHP

**Comment by nielsengelen** [comment]
This is related due to IIS not supporting the .htaccess file which needs to be rewritten. I will update the readme with the correct steps to perform this. Normally the guide explained on https://blogs.msdn.microsoft.com/azureossds/2015/04/23/converting-apache-htaccess-rules-to-iis-web-config-using-iis-manager-for-azure-websites/ should be sufficient.

**Comment by PleXi00** [comment]
thanks it works !

**Comment by charris-crs** [comment]
Hello
We have the same issue with an Linux OVA pre-configured vm.
http://localhost/exchange doesn't exist, we can force it with http://localhost/exchange.php
however there are no dates in the calendar and so no restore points.
It looks like the user admin@domain.co.uk cannot pull data from the VBO365 server repository
(same issue with Sharepoint and OneDrive)

thanks

**Comment by nielsengelen** [comment]
@charris-crs Make sure mod_rewrite is enabled for Linux. Have a look at the following guide: https://www.e2enetworks.com/help/knowledge-base/how-to-enable-mod_rewrite-on-apache-on-centos/

In regards to the tenant login not receiving data, make sure you enabled the RESTful API service as well as  authentication within the VBO365 console general options.

**Comment by charris-crs** [comment]
Hello Niels
Thanks for your prompt response 
I have checked the  mod_rewrite is enabled and rebooted the server
The httpd -V command showed that it couldn't find the FQDN so was using an IP v6 address.
I have specifically added the IPv4 address under server name using port80
I can open the exchange page but still have to specify exchange.php
There are no restore points showing  and the date is set to 1/1/1970. If I select this date and click restore it advises that the date of the first backup - this implies there is some kind of connection but no details
Authentication ans Rest API are both enabled on VBO365 server.

Thanks
Clive

**Comment by nielsengelen** [comment]
I presume you are running the latest VBO and are facing the issue as described in #12. 

The solution to this is to request the hotfix via Veeam support. Please open up a Veeam case and request the hotfix related to bug: 158283.
