### ISSUE TITLE
SharePoint Subsite (Restore session Expired)

### ISSUE THREAD

**Issue by Kaveerp** [nielsengelen/vbo365-rest#60]
Hi Nielsengelen

Thank you the fantastic Portal, please advise if you have solved the issue for "Session Expired".
I recieve this error everytime I open a SharePoint Subsite
![Session Error](https://user-images.githubusercontent.com/67784894/86459542-39d73200-bd27-11ea-9b55-02ec9a9d34f9.PNG)

Please can you advise accordingly ...
Kind Regards
Kaveer

**Comment by nielsengelen** [comment]
Could it be the specific subsite you are trying to reach is just a root site (meaning https://yourorg.sharepoint.com/subsite instead of https://yourorg.sharepoint.com/sites/subsite).

**Comment by Kaveerp** [comment]
Hi neilsengelen

It seems like it's all the the SharePoint subsites that I try click on that
displays the Session Error.

Kind Regards
Kaveer

**Comment by Kaveerp** [comment]
This happens as an admin, I have SharePoint admin privileges.

**Comment by nielsengelen** [comment]
I will have to look into this for a while to figure out the issue.

**Comment by Kaveerp** [comment]
Okay thank you , much appreciated.

**Comment by Kaveerp** [comment]
Hi neilsengelen

I see this request has been closed, have you managed to resolve this issue?

Kind regards
Kaveer

**Comment by nielsengelen** [comment]
Seems I closed the wrong one. I'm still looking into this.

**Comment by Kaveerp** [comment]
Okay great thank you, please advise when you have found a solution.

Kind Regards
Kaveer

**Comment by Kaveerp** [comment]
Hi nielsengelen

Please advise if you have any feedback\ solution for this case ?

Kind Regards
Kaveer

**Comment by nielsengelen** [comment]
Most likely you are facing an issue where the restore session gives back other data and this results in the error. I would need to have some more insight via logs if possible. Could you reach out to me via niels.engelen@veeam.com so we can follow it up via there?

**Comment by Kaveerp** [comment]
Okay great will do , Do you require the logs to look at ?

Kind Regards
Kaveer

**Comment by nielsengelen** [comment]
Resolved in 4.1 release (https://github.com/nielsengelen/vbo365-rest/releases/tag/v4.1).
