### ISSUE TITLE
Setting Settup vbo-365 rest

### ISSUE THREAD

**Issue by Anggakhalifah** [nielsengelen/vbo365-rest#61]
hi @here

i try to use Self-Service Web Portal vbo365 in windows server 2019 standard.

the steps I take are based on the guidelines.

i use iis version 10, php 7.4.1, composer already installed with version 1.10.8.

but when i open setup.php show error (attached), i try change with IP and Hostname server still same error.

are there any steps missed? or are there incomplete requirements?

![composer install in local](https://user-images.githubusercontent.com/17749072/86906553-ebb69a00-c13d-11ea-83ba-14aee5d7139f.jpg)

![error](https://user-images.githubusercontent.com/17749072/86905884-ead13880-c13c-11ea-8d93-df6c3069a5f2.jpg)

**Comment by nielsengelen** [comment]
Could you try to use the attached web.config file and see if it works? Remove the .txt extension as GitHub doesn't allow to add .Config files.

[Web.Config.txt](https://github.com/nielsengelen/vbo365-rest/files/4890336/Web.Config.txt)

**Comment by Anggakhalifah** [comment]
thanks for respon @nielsengelen , already add config files and can acces setup.php but still blank when change page to index.php

![image](https://user-images.githubusercontent.com/17749072/86919628-bb2d2b00-c152-11ea-9e66-657cb7e5c117.png)
![image](https://user-images.githubusercontent.com/17749072/86919699-d7c96300-c152-11ea-9766-88c9a6d288d5.png)

**Comment by nielsengelen** [comment]
Did you run the composer command? From the looks of it, CSS is missing which may cause the issue.

**Comment by Anggakhalifah** [comment]
okay thanks alot @nielsengelen , I forgot to have it
change the directory where the composer run. 

![image](https://user-images.githubusercontent.com/17749072/86920549-26c3c800-c154-11ea-8d98-faf82f5fcca7.png)


now I can open the page. 👍

**Comment by Anggakhalifah** [comment]
hello @nielsengelen ,

same trouble with issue#8, for htaccess in iis after import can i merge with web.config before? 

for menu in page index already work, but linked for exchange, onedrive and sharepoint is not work.

![image](https://user-images.githubusercontent.com/17749072/86996289-726a8600-c1d5-11ea-8d23-2ae6d32a3ad0.png)
![image](https://user-images.githubusercontent.com/17749072/86996307-80200b80-c1d5-11ea-93e2-4033cca877c1.png)

**Comment by Anggakhalifah** [comment]
this trouble solved when i import htaccess.

is it better to merge it with the previous config or can it be separated?

**Comment by Anggakhalifah** [comment]
hi @nielsengelen , i try backup and restore is succes, but when i _view_  sub menu session log in activity log is not display anything. Are there any wrong steps?

![image](https://user-images.githubusercontent.com/17749072/87014075-c84f2600-c1f5-11ea-858c-3c440abb85e9.png)

**Comment by nielsengelen** [comment]
This should provide you a popup with the details. Are you running javascript for some parts maybe?

**Comment by Anggakhalifah** [comment]
i create new fresh server to testing this, so server just use to install vbo365 and install environment for the web vbo

**Comment by nielsengelen** [comment]
@Anggakhalifah the activity log is just a copy of what you can see in the GUI under sessions. I have not seen the popup issue before. Any chance you can send me an e-mail via niels.engelen@veeam.com so we can try to debug it that way? Will be easier this way. Thanks!

**Comment by Anggakhalifah** [comment]
okay niels, i will contact in mail.

Thanks alot for respons
