### ISSUE TITLE
HTTP Error 404.3 - Not Found

### ISSUE THREAD

**Issue by mritsurgeon** [nielsengelen/vbo365-rest#62]
Hey Niels

getting: The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map

Not sure what Ive missed here ?
![VBO dash error](https://user-images.githubusercontent.com/59644778/87289457-f46fed00-c4fc-11ea-8610-15365c7bde82.PNG)

**Comment by nielsengelen** [comment]
Did you run the git clone command correctly or download it as a zip? This means the setup file is missing in the folder.

**Comment by mritsurgeon** [comment]
Git clone to inetpub then rename to wwwroot 

Setup.php is is directory C:\inetpub\wwwroot\setup.php
![fail1](https://user-images.githubusercontent.com/59644778/87391271-b7faca80-c5aa-11ea-8b55-d36af840a505.PNG)
![fail 2](https://user-images.githubusercontent.com/59644778/87391279-be894200-c5aa-11ea-8316-eb857d3535f7.PNG)

**Comment by nielsengelen** [comment]
Just to be sure did you install PHP on the server to work with IIS? It looks like 404.3 means the server doesn't recognize the PHP file.

**Comment by mritsurgeon** [comment]
Hey Niels 

![image](https://user-images.githubusercontent.com/59644778/87649956-401ad480-c751-11ea-8927-6826a8198dc7.png)

**Comment by nielsengelen** [comment]
Can u add the PHP handler as described in https://stackify.com/how-to-host-php-on-windows-with-iis/ under "Installing PHP on IIS manually"? It looks like this one is missing in the specific configuration and therefor it fails to load.

**Comment by mritsurgeon** [comment]
Thanks Niels

Was trying to automate all your steps through single script ...

Was using choco install php --force -y

Changed to  ( After: choco install Webpi )

WebPICMD.exe /Install /Products:PHP56 /AcceptEULA

Thanks all works

**Comment by nielsengelen** [comment]
Thanks for the update. Good information for me to know as well.
