### ISSUE TITLE
Multiple back end connection

### ISSUE THREAD

**Issue by BIjuMA** [nielsengelen/vbo365-rest#63]
**Is your feature request related to a problem? Please describe.**
This is not about reporting an issue. 

**Describe the solution you'd like**
Can this wonderful solution support multiple servers as backed? 
Eg in config.php: 
$host = 'Hostone.fqdn.net'; HostTwo.fqdn.net
We have exchange backup on one server host and OneDrive, SP on another 

Is there any option to allow non administrators to login to the web interface and access only their emails and
Is there any way to search emails with keywords, to or/and from or combinations like dates etc? (like Compliance search)

Thanks again
Biju

**Comment by nielsengelen** [comment]
Multiple is not supported right now. Is there a reason behind using 2 servers? You could use multiple proxies/repositories to store the data separately.

Only e-mail access for specific accounts is not possible (this would require a lot of custom work). Search for specific keywords is also not implemented but is something on the longer todo list (has been requested before).
