### ISSUE TITLE
Exchange/Sharepoint - RHS restore options not working

### ISSUE THREAD

**Issue by crollorc** [nielsengelen/vbo365-rest#64]
**Describe the bug**
RHS restore options are not working in Exchange and Sharepoint.

**To Reproduce**
Using v4.1 to browse backed up exchange mails.

Clicking the tickbox beside any mail and selecting each of the top left 'restore selected' options works.

However selecting any of the restore options to the right hand side of the mail with or without the tickbox selected simply results in the web page reloading.

**Expected behavior**
The RHS options should work.

**Screenshots**
Working options ...
![image](https://user-images.githubusercontent.com/4221897/90884711-27cd5380-e3a8-11ea-8b92-9e16b1f8a566.png)

Failing options...
![image](https://user-images.githubusercontent.com/4221897/90884794-4e8b8a00-e3a8-11ea-8de9-98634edee35a.png)

**Comment by nielsengelen** [comment]
@crollorc I'll need some time to investigate this and will report back with my findings.

**Comment by nielsengelen** [comment]
@crollorc Bug confirmed, thanks for reporting. I will update here once I published the fix.

**Comment by nielsengelen** [comment]
@crollorc I've published a fix. You will need to clone/download the 3 files from commit https://github.com/nielsengelen/vbo365-rest/commit/a013f2fdf32e783ae6c0762758ed12076c389fd0 (exchange.php, onedrive.php, sharepoint.php).

**Comment by crollorc** [comment]
@nielsengelen  

thanks for your help.

this seems to be working now for my tests of exchange.php and sharepoint.php. 

i'll open tickets for a few other issues i've noticed.
