### ISSUE TITLE
Sharepoint - web interface taking much longer than Veeam explorer to load sites/libraries

### ISSUE THREAD

**Issue by crollorc** [nielsengelen/vbo365-rest#66]
**Describe the bug**
For a 1TB sharepoint backup, opening the site/content takes ~ 20s on Veeam Explorer for Sharepoint and opening a library below this takes < 5s in the same application.

Opening the same site or any of the associated libraries in the self service web interface consistently takes 40s+.

**To Reproduce**
Click on a site or library on the LHS and time the HTTP request. 

Open the same site or library in Veeam Explorer for Sharepoint and time the request.

**Expected behavior**
The web interface should not take double the time over the explorer to access the site. Also accessing libraries is relatively fast in Veeam explorer but takes 10 times longer in the web interface in my tests.

**Screenshots**
![image](https://user-images.githubusercontent.com/4221897/91719444-40e6b900-eb8d-11ea-9adf-d7b5be6cc75d.png)

![image](https://user-images.githubusercontent.com/4221897/91719459-45ab6d00-eb8d-11ea-82ce-e37683a4ac5e.png)

**Additional context**
If you can provide the details on the sequence of API calls required I can do some Swagger UI testing.

**Comment by nielsengelen** [comment]
The code for the calls is in veeam.class.php file. I wrote a [blog post series](https://foonet.be/veeam-backup-for-microsoft-office-365-restful-api-series/) on how to work with the API (using Swagger), and a part on [SharePoint](https://foonet.be/2019/02/27/veeam-backup-for-microsoft-office-365-restful-api-sharepoint-restores/). Once you've started the session and got the ID, you can get the lists/documents via the responding GET call on the required site. 

[Getting the sites](https://helpcenter.veeam.com/docs/vbo365/rest/get_organizations_id_sites.html?ver=40)
[Getting the documents](https://helpcenter.veeam.com/docs/vbo365/rest/get_sites_id_documents.html?ver=40)

The portal just uses these calls so depending on how fast the API service replies, output is parsed.
