### ISSUE TITLE
Sharepoint - some documents missing from folders

### ISSUE THREAD

**Issue by crollorc** [nielsengelen/vbo365-rest#67]
**Describe the bug**
In many cases, I've found that files were missing when browsing sharepoint backup folders.

However, I could see the files were included in veeam.php POST responses listed in the Chrome Developer Tools Network tab.

It looks like you are missing some code and I found that including the following snippet from elsewhere in your code seemed to correct this issue:
> 
> [root@veeam-o365-web1 html]# diff sharepoint.php.31082020.new sharepoint.php
1241a1242,1265
>
>                       if (typeof responsedocuments !== 'undefined' && responsedocuments.results.length !== 0) {
>                           <?php
>                           if (strcmp($type, 'list') === 0) {
>                           ?>
>                           fillTableDocuments(responsedocuments, siteid, 'items');
>                           <?php
>                           } else {
>                           ?>
>                           fillTableDocuments(responsedocuments, siteid, 'documents');
>                           <?php
>                           }
>                           ?>
>                       }
>                       if ((typeof responsefolders !== 'undefined' && responsefolders.results.length == '30') || (typeof responsedocuments !== 'undefined' && responsedocuments.results.length == '30')) {
>                           $('a.load-more-link').removeClass('hide');
>                           $('a.load-more-link').data('offset', 30);
>                           $('a.load-more-link').data('folderid', folderid);
>                       } else {
>                           $('a.load-more-link').addClass('hide');
>                       }
>                       $('#loader').addClass('hide');
>                       enableTree();
`

**Comment by nielsengelen** [comment]
I'm not sure what is different but it could be the setTimeout function in javascript causes an issue there. The logic behind it is the following:
- folder info gets requested and the tree is created
- based upon list or libary, we get documents or items (with a delay of 2000 milliseconds to assure we get data from the API in time)
- items/documents get added to the table (with a delay of 3000 milliseconds to assure we get data from the API in time)

Am I correct that you've copied this code in the first setTimeout function?

**Comment by crollorc** [comment]
> Am I correct that you've copied this code in the first setTimeout function?

yes, sorry. here is the complete setTimeout:
>        setTimeout(function(e) {
>                <?php
>                if (strcmp($type, 'list') === 0) {
>                ?>
>                $.post('veeam.php', {'action' : 'getsharepointitems', 'rid' : rid, 'siteid' : siteid, 'type' : 'Items', 'folderid' : folderid}).done(function(data) {
>                        responsedocuments = JSON.parse(data);
>                });
>                <?php
>                } else {
>                ?>
>                $.post('veeam.php', {'action' : 'getsharepointitems', 'rid' : rid, 'siteid' : siteid, 'type' : 'Documents', 'folderid' : folderid}).done(function(data) {
>                        responsedocuments = JSON.parse(data);
>
>                        // LOCAL - START
>                        if (typeof responsedocuments !== 'undefined' && responsedocuments.results.length !== 0) {
>                            <?php
>                            if (strcmp($type, 'list') === 0) {
>                            ?>
>                            fillTableDocuments(responsedocuments, siteid, 'items');
>                            <?php
>                            } else {
>                            ?>
>                            fillTableDocuments(responsedocuments, siteid, 'documents');
>                            <?php
>                            }
>                            ?>
>                        }
>                        if ((typeof responsefolders !== 'undefined' && responsefolders.results.length == '30') || (typeof responsedocuments !== 'undefined' && responsedocuments.results.length == '30')) {
>                            $('a.load-more-link').removeClass('hide');
>                            $('a.load-more-link').data('offset', 30);
>                            $('a.load-more-link').data('folderid', folderid);
>                        } else {
>                            $('a.load-more-link').addClass('hide');
>                        }
>                        $('#loader').addClass('hide');
>                        enableTree();
>                        // LOCAL - STOP
>                });
>                <?php
>                }
>                ?>
>        }, 2000);

**Comment by nielsengelen** [comment]
Thanks for clearing out. I will look into it. Thanks for reporting!

**Comment by nielsengelen** [comment]
@crollorc I'm trying to duplicate the behavior. Could you tell me if this happened in a library or list and if you have an idea on the amount of items/documents in the list?

**Comment by crollorc** [comment]
@nielsengelen do you have private email i could send screenshots etc. to rather than pasting them in here?

**Comment by nielsengelen** [comment]
Sure, just send them to niels.engelen@veeam.com. Thanks!
