### ISSUE TITLE
advanced find

### ISSUE THREAD

**Issue by crollorc** [nielsengelen/vbo365-rest#69]
**Is your feature request related to a problem? Please describe.**
How can a tenant find one email amongst millions with this code?

The Veeam Explorer for MS Exhchange/Sharepoint/OneDrive have an 'advanced find' to help find exactly whats required.

Could similar functionality be added to this code? 

Would API changes also be required?

**Additional context**
![Capture_censored](https://user-images.githubusercontent.com/4221897/93584693-90a2ee00-f99d-11ea-82fb-5a2b1d6ebcb5.jpg)

**Comment by crollorc** [comment]
Thanks Niels. 

Would you mind telling me how would eDiscovery be implemented?

Could it be done using the current API or is it on the API roadmap?

**Comment by nielsengelen** [comment]
It can be done already (see [the RESTful API user guide](https://helpcenter.veeam.com/docs/vbo365/rest/searching_items_by_restore_session_mailbox_and_folder_id.html?ver=40)) so it should be possible to have the same options as the GUI.

**Comment by crollorc** [comment]
The API docs linked only cover searching based on from and to addresses ("query": "from: user_X to: user_Y"). 

Would the more sophisticated search options available in 'advanced find' also be supported? If so, what format should be used?

**Comment by nielsengelen** [comment]
They are supported. The documentation should be updated soon with all the options but you can use things like cc, bcc, sent, received,... I don't have the full list myself yet though.

**Comment by tar565** [comment]
Sorry for jumping in on this thread but can you tell me what the full list of search options are? As of now, I'm searching by 'to', 'from' and 'subject', e.g. (("query": "from: user_X to: user_Y subject: XXXX")) but I would like to search by date, e.g. ("query": "from: user_X to: user_Y subject: XXX sent: <<date range>>") also. Is this possible?

**Comment by nielsengelen** [comment]
U should be able to use sent and received for these. I'm not sure if multiple are supported or a maximum of 2 though.

Veeam's documentation should have the full list upon v5 release.

**Comment by tar565** [comment]
Can you tell me when v5 is due for release?

**Comment by nielsengelen** [comment]
@tar565 still working on testing everything and fixing minor bugs. Due to all the restore scenario's (basic and MFA options), this takes some time. I hope to publish the code later this week or next week.
