### ISSUE TITLE
Working with the Portal

### ISSUE THREAD

**Issue by malcolmwren** [nielsengelen/vbo365-rest#7]
Hi there
I have installed the portal on a server, the same server that is running the office 365 VBO and i can login to the portal as the server administrator that is also the admin for the VBO product itself.

If i try to login using the same credentials used for the backup of the organisation or the credentials of one of the mailboxes being backed up i get the following

Error
The username or password provided is incorrect. Make sure you are logging in with your Office 365 account.

Is there documentation available on how i can get past this step?

regards
Malcolm

**Comment by nielsengelen** [comment]
Hi Malcolm,

You will need to use the admin login which has been used to add the tenant's organization in the GUI. It is currently not possible to use any other login yet.

If you added the organization with veeam@mydomain.com, this will be the username you'll need to use.

**Comment by malcolmwren** [comment]
Hi there
Thanks, if the organisation was added with an “onmicorost.com” account because its not a licensed account but has permissions, will that be an issue?

I have 2 different organisations that I am testing the portal with.

Org1
Logging on with the tenants organisation address of veeam.backup@amidata.onmicrosoft.com<mailto:veeam.backup@amidata.onmicrosoft.com> displays the URL localhost/exhchange and this throws a http error 404 page not found

Org2
Logging on with the tenants organisation address of mwren@wrenmaxwell.com.au<mailto:mwren@wrenmaxwell.com.au> displays the URL localhost/exhchange and this throws a http error 404 page not found

So  I am assuming for the portal to get full access the login for the tenancy needs to be a fully licensed user account dedicated to the backup process and not used for general use or an unlicensed account

Regards
Mal

**Comment by malcolmwren** [comment]
The conversion to the web.config file resolved the issue.
So from my take this portal has some good features but my assumption here is that we can only restore individual items within a mailbox and not a whole folder within a mailbox or even a specific mailbox in total?

The process of restoring a whole folder or mailbox can only be done by accessing the veeam365 console ??

**Comment by nielsengelen** [comment]
Correct, this is already tracked as a feature request in #2 and will be published once available.

**Comment by nielsengelen** [comment]
Marked as change for next version/update in reference to #2.
