### ISSUE TITLE
Change color to my tenant view

### ISSUE THREAD

**Issue by GiuliaCarafone** [nielsengelen/vbo365-rest#70]
Hi @nielsengelen ,
Could you please tell me if it is possible change tenant view colors?
If it is possible, what is the path and the name of the file where I've to do modify?
Thanks and Regards,
Giulia

**Comment by nielsengelen** [comment]
Hi, this isn't possible within the current style. Could you tell me which colors you would like to change with a filtered screenshot so I can look into a workaround?

**Comment by GiuliaCarafone** [comment]
Hi,
we want to customize the portal: we have two organizations, and we want to change the color of black part on the following screenshot with different color for each one. It is possible?
[cid:image001.jpg@01D691B8.B758ABE0]

In this case I have log on as tenant administrator.
Many thanks,
Giulia

**Comment by nielsengelen** [comment]
Hi Giulia, 

The image isn't loading. Could you drop me an e-mail via niels.engelen@veeam.com and we can pick it up via there?

**Comment by GiuliaCarafone** [comment]
Hi @nielsengelen , 
Did you received my email?
Let me know if not.

**Comment by nielsengelen** [comment]
Hi @GiuliaCarafone - yes I did and just replied. Sorry for not replying directly. For now, I'll take this as a feature request and close the request.
