### ISSUE TITLE
clipboard.min.js missing

### ISSUE THREAD

**Issue by poulpreben** [nielsengelen/vbo365-rest#72]
**Describe the bug**
The application depends on `/js/clipboard.min.js`, but it is not included in the code base. This seems to affect the copy MFA login token functionality.

**To Reproduce**
1. Open portal
2. Inspect Element
3. See that the request for `/js/clipboard.min.js` throws 404.

**Comment by nielsengelen** [comment]
File has been committed in https://github.com/nielsengelen/vbo365-rest/commit/ba06bb6223f76666c0e0e0d0d1a4ddc949581d80
