### ISSUE TITLE
Some suggested changes for the portal

### ISSUE THREAD

**Issue by henkblik** [nielsengelen/vbo365-rest#73]
Hi Niels,

I have some remarks concerning the portal.
First let me thank you for the portal it self, is is a very good starting
point for using the API if the veeam backup server.
However, I found some bugs and have some sugestions of improvement.

In the first version ther was a limit of 1000 for obtaining the Mailboxes,
Sites and Onedrives
Now no limit is given and the limit set by the API and is 30, that is by far
to low for our organisation.
After pressing the button "explore last backup" we only see 30
sites/mailboxes/onedrives. The button to load more sites is shown when 50 or
more sites are obtained by the previous call. This should be 30.
In sharepoint.php the code for the button seems wrong to me for the
data-offset,

It is:

data-offset="' . count($users['results'])

And should be:

data-offset="' . count($sites['results'])

Should this limit for getting the sites/mailboxes/onedrive not be much higher
or configurable depending on the kind of organisation?
I would prefer an alphabetic list with al mailboxes/sites/onedrives instead of
a partial sorted list follwed by one or more unsorded parts obtained by
"load next items". It takes however a long time to retriev all sites/mailboxes/
ondrives.

Suggestion for user experince performance improvement using caching

We tried to improve the startup time of a restore for an organistion with
over 2000 sharepoint sites:

Using the first version and version 4.1 of the portal we experienced a long
wait after pressing "start restore" or "explore last backup" This is for the
biggest part caused by the request to get all the sites/mailboxes/onedrives.
We had a good experience by using an external caching that is refreshed once a
day using cron

to refresh the cache we use the following code:

/* extract from our code */

$veeam = new VBO($host, $port, $version);

$veeam->login ($user, $pass);

$org = $veeam->getOrganizations ();
//print_r ($org);
openlog ("veeam-portal_cache_log", LOG_PID | LOG_PERROR, LOG_LOCAL0);

$pit = date ('Y.m.d h:i', time ());

/* cache sharepoint sites */

$json = '{ "explore": { "datetime": "' . $pit . '", "type": "vesp", "ShowAllVersions": "true", "ShowDeleted": "true" } }';
$rid = $veeam->startRestoreSession ($json, $org[0]['id']);
$sites = $veeam->getSharePointSites ($rid['id']);
$veeam->stopRestoreSession($rid['id']);
$site_count = count($sites['results']);

$mysqli = new mysqli ($db_host,  $db_user,  $db_passwd, $db);
if ($mysqli->connect_errno)
{
    syslog (1, "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error);
}
else
{
    $sql = "delete from sites where oid = ?";
    if ($stmt = $mysqli->prepare ($sql))
    {
            if (!$stmt->bind_param ('s', $org[0]['id']))
                syslog (1, "Binding parameters '$sql' failed: (" . $stmt->errno . ") " . $stmt->error);
            $stmt->execute();
    }
    else
        syslog (1, $error = $mysqli->errno . ' ' . $mysqli->error);
    $sql = "insert into sites (id, name, oid) values (?, ?, ?)";
    if ($stmt = $mysqli->prepare ($sql))
    {
        for ($i = 0; $i < $site_count; $i++)
        {
                if (!$stmt->bind_param ('sss', $sites['results'][$i]['id'], $sites['results'][$i]['name'], $org[0]['id']))
                    syslog (1, "Binding parameters '$sql' failed: (" . $stmt->errno . ") " . $stmt->error);
                if (! $stmt->execute ())
                    syslog (1, "Execute '$sql' failed: (" . $stmt->errno . ") " . $stmt->error);
        }
            print "sites $i items cached\n";
    }
    else
        syslog (1, $error = $mysqli->errno . ' ' . $mysqli->error);

    /* repeat for mailboxes and onedrives */
}
$mysqli->close ();

/* end of extract */

The code in sharepoint.php was altered

the codeline:

$sites = $veeam->getSharePointSites($rid);

is altered in:

                    openlog ("veeam-portal_log", LOG_PID | LOG_PERROR, LOG_LOCAL0);
                    $result = null;
                    $mysqli = new mysqli($db_host,  $db_user,  $db_passwd, $db);
                    if (! $mysqli->connect_errno)
                    {
                        if ($stmt = $mysqli -> prepare ("select * from sites where oid = ?"))
                        {
                            if ($stmt -> bind_param('s', $org['id']))
                            {
                                if ($stmt -> execute())
                                {
                                    $result = $stmt->get_result();
                                }
                                else
                                    syslog (LOG_NOTICE, "mysqli execute" .   $stmt->error);
                            }
                            else
                                syslog (LOG_NOTICE,  "mysqli bind" . $stmt->error);
                        }
                        else
                            syslog (LOG_NOTICE, "mysqli prepare" .  $mysqli->error);
                    }
                    else
                        syslog (LOG_NOTICE, "mysqli connect" . $mysqli->connect_errno);
                    closelog ();
                    if ($result)
                    {
                        $i = 0;
                        $sites = array();
                        while ($site = $result->fetch_array())
                        {
                            $sites ['results'][$i]['id'] = $site ['id'];
                            $sites ['results'][$i]['name'] = $site ['name'];
                             $i ++;
                         }
                    }
                    if (! $result || ! $i)
                    {
                        syslog (LOG_NOTICE, "no data found in cache");
                        $sites = $veeam->getSharePointSites($rid);
                    }

/* end of alterde code in sharepoint.php */

In stead of using a mysql database for the cache it is possible to use a
normal file that is overwitten during the cache update.

Same way of caching is possible for onedrives and mailboxes

We have also experienced missing data in sharepoint libraries, enlarging the
timeout value in setTimeout from 2000 to 3000 solved that. Using setTimeout is
bad practice I think because you never know what the correct time is. You may
wait to long or to short. I have altered the code and use set Interval.

The following code from sharepoint.php in version 4.1 in the function
loadFolderItems(folderid, parent)

/* code form sharepoint. php */

        setTimeout(function(e) {
                <?php
                if (strcmp($type, 'list') === 0) {
                ?>
                $.post('veeam.php', {'action' : 'getsharepointitems', 'rid' : rid, 'siteid' : siteid, 'type' : 'Items', 'folderid' : folderid}).done(function(data) {
                        responsedocuments = JSON.parse(data);
                });
                <?php
                } else {
                ?>
                $.post('veeam.php', {'action' : 'getsharepointitems', 'rid' : rid, 'siteid' : siteid, 'type' : 'Documents', 'folderid' : folderid}).done(function(data) {
                        responsedocuments = JSON.parse(data);
                });
                <?php
                }
                ?>
        }, 2000);

    setTimeout(function(e) {
                if ((typeof responsefolders !== 'undefined' && responsefolders.results.length === 0) && (typeof responsedocuments !== 'undefined' && responsedocuments.results.length === 0)) {
                        $('#table-sharepoint-items tbody').append('<tr><td class="text-center" colspan="6">No items available in this folder.</td></tr>');
                }

        if (typeof responsefolders !== 'undefined' && responsefolders.results.length !== 0) {
            fillTableFolders(responsefolders, folderid, siteid);
        }

        if (typeof responsedocuments !== 'undefined' && responsedocuments.results.length !== 0) {
            <?php
            if (strcmp($type, 'list') === 0) {
            ?>
            fillTableDocuments(responsedocuments, siteid, 'items');
            <?php
            } else {
            ?>
            fillTableDocuments(responsedocuments, siteid, 'documents');
            <?php
            }
            ?>
        }

        if ((typeof responsefolders !== 'undefined' && responsefolders.results.length == '30') || (typeof responsedocuments !== 'undefined' && responsedocuments.results.length == '30')) {
            $('a.load-more-link').removeClass('hide');
            $('a.load-more-link').data('offset', 30);
            $('a.load-more-link').data('folderid', folderid);
        } else {
            $('a.load-more-link').addClass('hide');
        }

                $('#loader').addClass('hide');
                enableTree();
    }, 3000);

/* end of code from shatepint.php */

/* extract from modified code in sharepoint.php */

    function fill (){

        if ((typeof responsefolders === 'undefined') && (cnt ++  < 10))
            return;
        clearInterval (id);
        console.log ("loadFolderItems responsefolders = " + responsefolders + ", ", typeof responsefolders + " cnt = " + cnt);

        <?php
        if (strcmp($type, 'list') === 0) {
        ?>
        $.post('veeam.php', {'action' : 'getsharepointitems', 'rid' : rid, 'siteid' : siteid, 'type' : 'Items', 'folderid' : folderid}).done(function(data) {
            responsedocuments = JSON.parse(data);
        });
        <?php
        } else {
        ?>
        $.post('veeam.php', {'action' : 'getsharepointitems', 'rid' : rid, 'siteid' : siteid, 'type' : 'Documents', 'folderid' : folderid}).done(function(data) {
            responsedocuments = JSON.parse(data);
        });
        <?php
        }
        ?>
    };

    var cnt2 = 0;
    var id2 = setInterval (fill2, 500);

    function fill2 () {
        if (((typeof responsefolders === 'undefined') || (typeof responsedocuments === 'undefined')) && (cnt2 ++  < 15))
            return;
        clearInterval (id2);
        console.log ("loadFolderItems responsefolders = " + responsefolders + ", ", typeof responsefolders + " responsedocuments = " + responsedocuments + ", " + typeof responsedocuments + " cnt = " + cnt);

        if ((typeof responsefolders !== 'undefined' && responsefolders.results.length === 0) && (typeof responsedocuments !== 'undefined' && responsedocuments.results.length === 0)) {
            $('#table-sharepoint-items tbody').append('<tr><td class="text-center" colspan="6">No items available in this folder.</td></tr>');
        }

        if (typeof responsefolders !== 'undefined' && responsefolders.results.length !== 0) {
            fillTableFolders(responsefolders, folderid, siteid);
        }

        if (typeof responsedocuments !== 'undefined' && responsedocuments.results.length !== 0) {
            <?php
            if (strcmp($type, 'list') === 0) {
            ?>
            fillTableDocuments(responsedocuments, siteid, 'items');
            <?php
            } else {
            ?>
            fillTableDocuments(responsedocuments, siteid, 'documents');
            <?php
            }
            ?>
        }

        if ((typeof responsefolders !== 'undefined' && responsefolders.results.length == '30') || (typeof responsedocuments !== 'undefined' && responsedocuments.results.length == '30')) {
            $('a.load-more-link').removeClass('hide');
            $('a.load-more-link').data('offset', 30);
            $('a.load-more-link').data('folderid', folderid);
        } else {
            $('a.load-more-link').addClass('hide');
        }

        $('#loader').addClass('hide');
        enableTree();
    };

/* end of extract of modified code */

explanation: I use a value of 500 milliseconds for the interval
If the interval has expired a check is done for the responsfolders.
(and responsedocuments in the second case) and the value of a counter.

If typeof responsefolders === 'undefined' and cnt < 10 the interval is
continued for the next 500 milis.

If typeof responsefolders === 'undefined' or the cnt exceedes 10 then the
interval is cleared and the function continues with processing.

A line to the console is written shown the typeof responsfolders and
responsfolders, this mainly to check if the thershol for cnt is high enough

If the threshold for cnt (and cnt2) is high enough we can be reasonably sure
that we waited long enough for the server to return the data. I think it
should be safe to leave the check on cnt and cnt2 out but I am not sure what
happens if the backup server does not respond at all.

Some other ideas:

If a restore is started we can remove all links from the page that are not
relevant to the restore. So the links for home, sharepoint, onedrive ,
mailboxes, logout can removed until "stop restore" is clicked.

During the start of a restore the "start restore" and "explore last backups"
buttons are disabled. I think it is better to gray out the entire page and show
a (large) busy indicate so the user kwow they have to wait some (long) time.

I hope you find the above suggestions usefull and use the in the future vesions
of the portal

best regards,

Henk Blik

**Comment by nielsengelen** [comment]
Thanks for reporting the counter bug and the change of $users to $sites. I notice that in the veeam class file, I forgot to add the limit parameter to the getSharePointSites function. 

Regarding the sorting of the accounts; this is only possible if everything is pre-loaded which adds a high load on the server in terms of API calls (or use a cache as suggested). Requesting 1000(0) items can take some time and therefore right now this limitation is somewhat forced. VBO v5 should however improve this and at that point in time, I will adjust the standard counter to a higher number. 

I don't plan on adding a database or file structure for caching though. A database would provide a lot of possibilities but it would also make this project more complex when it comes to installing, maintaining and security. The same for using a local file as a cache (security questions arise). 

On using setTimeout or setInterval, I am aware of the risk with setTimeout and if you look at the 4.2 code for MFA, you'll notice that setInterval is being used there. It is something that I'll adjust in a next version as well since it just works so much better. The setTimeout code is something from v2 or v3 and has so far served most users well.

**Comment by nielsengelen** [comment]
I will close this feedback post.

The next version will have a few of these improvements:
- Starting a restore now shows a message 
- If a restore session is running, other pages are hidden (until I implement a multiple restore session handler)
- setTimeout has been replaced by utilizing "then" feature of jQuery
- Added an option to the config file to specify the default item limit to show for Exchange, OneDrive, and SharePoint (default is 250)

Sorting and only showing items with specific letters is not yet added. It will require enhancements within the VBO API sadly.
