### ISSUE TITLE
SharePoint Restore no longer working

### ISSUE THREAD

**Issue by carokiel** [nielsengelen/vbo365-rest#74]
Hi Niels,
after upgrading to the last build, I can get a false error message:
When I select any organization, I get the response "No SharePoint sites found for this organization." When I click on "Explore last backup", I get the results and can run restores.
Rebooting the VBO and the webserver did not help.

Thank you,
Caroline

**Comment by nielsengelen** [comment]
Hi Caroline, did you run multiple backups for this organization already?

**Comment by carokiel** [comment]
Yes, we backup these orgs for months.

________________________________
Caroline Kiel

PingUs Solutions

CEO



Tel.:
Fax:
Mobil:
E-Mail:

+49 33056 401-111<tel:+49%2033056%20401-111>
+49 33056 401-190<tel:+49%2033056%20401-190>
+49 172 3232 800<tel:+49%20172%203232%20800>
Caroline.Kiel@pingus.de<mailto:Caroline.Kiel@pingus.de>


Marienstr. 1a
D-16552 Mühlenbecker Land
Ortsteil Schildow
https://www.pingus.de


________________________________
PingUs Solutions GmbH & Co. KG

Geschäftsführung (Managing Partners)

Anja Kiel, Caroline Kiel

Steuernummer (Tax ID)

053/161/09049

UID-Nr. (VAT-No.)

DE 813 720 069

Amtsgericht (County Court)

Neuruppin HRA 1440 OPR

________________________________
Important Note:
This e-mail may contain trade secrets or privileged, undisclosed or otherwise confidential information. If you have received this e-mail in error, you are hereby notified that any review, copying or distribution of it is strictly prohibited. Please inform us immediately and destroy the original transmittal. Thank you for your cooperation.
.
[Logo PingUs Solutions]<https://docks.pingus.de/>
Von: nielsengelen <notifications@github.com>
Gesendet: Donnerstag, 29. Oktober 2020 09:20
An: nielsengelen/vbo365-rest <vbo365-rest@noreply.github.com>
Cc: Caroline Kiel <Caroline.Kiel@pingus.de>; Author <author@noreply.github.com>
Betreff: [*Newsletter*] [Ext] Re: [nielsengelen/vbo365-rest] SharePoint Restore no longer working (#74)


Hi Caroline, did you run multiple backups for this organization already?
