### ISSUE TITLE
Exporting to .PST gives guzzle errors

### ISSUE THREAD

**Issue by PatyYe** [nielsengelen/vbo365-rest#75]
I'm trying to restore files from a restore Exchange session, however when I hit the ".PST" option I get the following error:
```
PHP Warning:  fseek(): supplied resource is not a valid stream resource in C:\inetpub\wwwroot\vendor\guzzlehttp\psr7\src\Stream.php on line 206
PHP Warning:  stream_get_contents(): supplied resource is not a valid stream resource in C:\inetpub\wwwroot\vendor\guzzlehttp\psr7\src\Stream.php on line 95
PHP Notice:  Trying to access array offset on value of type null in C:\inetpub\wwwroot\veeam.class.php on line 1501
```

Have you run into this issue before? The portal works fine with restoring singular .MSG files.

**Comment by nielsengelen** [comment]
Can u verify outlook is installed on the VBO server (it is required for exporting to PST)?

**Comment by PatyYe** [comment]
That's an quick answer, I can verify that Outlook is installed on the VBO server itself.
Is it running Outlook in the background as a back-end call?
Then I might need to check if the regular restore procedure works, if not I'll go ahead and fix that first.

**Comment by PatyYe** [comment]
We figured out there is an issue ongoing with the latest Oktober updates and Veeam Explorer.
Currently we raised a ticket at Veeam as we have the latest updates, which breaks the Explorer. 

Workaround at the moment is:
- Reinstall office, and prevent any updates. Which is for most business a no-go, including us.

**Comment by nielsengelen** [comment]
Thanks for reporting this. I was not aware of this and will do the test as well.
