### ISSUE TITLE
MFA Login Problem

### ISSUE THREAD

**Issue by dominikmze** [nielsengelen/vbo365-rest#76]
Hello,

if I want to log in with an MFA account, this does not work. I get the login code and then authenticate myself with Microsoft, but I am not logged into the interface afterwards. If I then enter the email address directly, I get the error message simple login in Microsoft.

Do you have a solution for that? I look forward to an answer.

**Comment by nielsengelen** [comment]
Can u confirm you are using the domain in the onmicrosoft.com format and are using the correct application? If an organization is added using MFA, logging in via the email address won't work.

**Comment by dominikmze** [comment]
Yes i use the domain from the company in the onmicrosof.com format. I copy this from my azure portal. 

I also used the same Application ID as the Veeam Backup Server.

In the REST log file I get the following error message: 

05.11.2020 17:41:07   31 (8008) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
05.11.2020 17:41:07   28 (7820) Validating certificate chain...
05.11.2020 17:41:07   28 (7820) Certificate chain validation successfully completed.
05.11.2020 17:41:07   28 (7820) Validating certificate claims...
05.11.2020 17:41:07   28 (7820) Certificate claims:
05.11.2020 17:41:07   28 (7820)   Veeam Software
05.11.2020 17:41:07   28 (7820) Validation failed. Certificate is not valid for host 127.0.0.1
05.11.2020 17:41:07   31 (8008)   Connection failed
05.11.2020 17:41:07   31 (8008) Error: Ein nicht gesicherter oder fehlerhaft gesicherter Fehler wurde vom anderen Teilnehmer empfangen. Den Fehlercode und Details finden Sie unter der inneren FaultException.
05.11.2020 17:41:07   31 (8008) Type: System.ServiceModel.Security.MessageSecurityException
05.11.2020 17:41:07   31 (8008) Stack:
05.11.2020 17:41:07   31 (8008) 
Server stack trace: 
   bei System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   bei System.ServiceModel.Channels.CommunicationObject.EndOpen(IAsyncResult result)

Exception rethrown at [0]: 
   bei Veeam.Engine.Wcf.PrimitiveServiceClient`1.Open(CancellationToken token)
   bei Veeam.Archiver.Integration.ArchiverConnector`2.CreateArchiverConnection(TE events, ICertificateValidator certificateValidator, IServiceConnectionConfig connectionConfig, Nullable`1 cancellationToken)
05.11.2020 17:41:07   31 (8008) Error: The server has rejected the client credentials.
05.11.2020 17:41:07   31 (8008) Type: System.ServiceModel.FaultException
05.11.2020 17:41:07   31 (8008) Stack:
05.11.2020 17:41:07   31 (8008) 
05.11.2020 17:41:07   31 (8008) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
05.11.2020 17:41:07   28 (7820) Validating certificate chain...
05.11.2020 17:41:07   28 (7820) Certificate chain validation successfully completed.
05.11.2020 17:41:07   28 (7820) Validating certificate claims...
05.11.2020 17:41:07   28 (7820) Certificate claims:
05.11.2020 17:41:07   28 (7820)   Veeam Software
05.11.2020 17:41:07   28 (7820) Validation failed. Certificate is not valid for host 127.0.0.1
05.11.2020 17:41:07   31 (8008)   Connection failed
05.11.2020 17:41:07   31 (8008) Error: Ein nicht gesicherter oder fehlerhaft gesicherter Fehler wurde vom anderen Teilnehmer empfangen. Den Fehlercode und Details finden Sie unter der inneren FaultException.
05.11.2020 17:41:07   31 (8008) Type: System.ServiceModel.Security.MessageSecurityException
05.11.2020 17:41:07   31 (8008) Stack:
05.11.2020 17:41:07   31 (8008) 
Server stack trace: 
   bei System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   bei System.ServiceModel.Channels.CommunicationObject.EndOpen(IAsyncResult result)

Exception rethrown at [0]: 
   bei Veeam.Engine.Wcf.PrimitiveServiceClient`1.Open(CancellationToken token)
   bei Veeam.Archiver.Integration.ArchiverConnector`2.CreateArchiverConnection(TE events, ICertificateValidator certificateValidator, IServiceConnectionConfig connectionConfig, Nullable`1 cancellationToken)
05.11.2020 17:41:07   31 (8008) Error: The server has rejected the client credentials.
05.11.2020 17:41:07   31 (8008) Type: System.ServiceModel.FaultException
05.11.2020 17:41:07   31 (8008) Stack:
05.11.2020 17:41:07   31 (8008) 
05.11.2020 17:41:07   31 (8008) Disconnecting from Veeam Backup for Office 365 server...
05.11.2020 17:41:07   31 (8008) Disconnecting from Veeam Backup for Office 365 server...
05.11.2020 17:41:25   31 (8008) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
05.11.2020 17:41:25   29 (1156) Validating certificate chain...
05.11.2020 17:41:25   29 (1156) Certificate chain validation successfully completed.
05.11.2020 17:41:25   29 (1156) Validating certificate claims...
05.11.2020 17:41:25   29 (1156) Certificate claims:
05.11.2020 17:41:25   29 (1156)   Veeam Software
05.11.2020 17:41:25   29 (1156) Validation failed. Certificate is not valid for host 127.0.0.1
05.11.2020 17:41:25   31 (8008)   Connection failed
05.11.2020 17:41:25   31 (8008) Error: Ein nicht gesicherter oder fehlerhaft gesicherter Fehler wurde vom anderen Teilnehmer empfangen. Den Fehlercode und Details finden Sie unter der inneren FaultException.
05.11.2020 17:41:25   31 (8008) Type: System.ServiceModel.Security.MessageSecurityException
05.11.2020 17:41:25   31 (8008) Stack:
05.11.2020 17:41:25   31 (8008) 
Server stack trace: 
   bei System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   bei System.ServiceModel.Channels.CommunicationObject.EndOpen(IAsyncResult result)

Exception rethrown at [0]: 
   bei Veeam.Engine.Wcf.PrimitiveServiceClient`1.Open(CancellationToken token)
   bei Veeam.Archiver.Integration.ArchiverConnector`2.CreateArchiverConnection(TE events, ICertificateValidator certificateValidator, IServiceConnectionConfig connectionConfig, Nullable`1 cancellationToken)
05.11.2020 17:41:25   31 (8008) Error: The server has rejected the client credentials.
05.11.2020 17:41:25   31 (8008) Type: System.ServiceModel.FaultException
05.11.2020 17:41:25   31 (8008) Stack:
05.11.2020 17:41:25   31 (8008) 
05.11.2020 17:41:25   31 (8008) Connecting to Veeam Backup for Office 365 server at 127.0.0.1:9194...
05.11.2020 17:41:26   29 (1156) Validating certificate chain...
05.11.2020 17:41:26   29 (1156) Certificate chain validation successfully completed.
05.11.2020 17:41:26   29 (1156) Validating certificate claims...
05.11.2020 17:41:26   29 (1156) Certificate claims:
05.11.2020 17:41:26   29 (1156)   Veeam Software
05.11.2020 17:41:26   29 (1156) Validation failed. Certificate is not valid for host 127.0.0.1
05.11.2020 17:41:26   31 (8008)   Connection failed
05.11.2020 17:41:26   31 (8008) Error: Ein nicht gesicherter oder fehlerhaft gesicherter Fehler wurde vom anderen Teilnehmer empfangen. Den Fehlercode und Details finden Sie unter der inneren FaultException.
05.11.2020 17:41:26   31 (8008) Type: System.ServiceModel.Security.MessageSecurityException
05.11.2020 17:41:26   31 (8008) Stack:
05.11.2020 17:41:26   31 (8008) 
Server stack trace: 
   bei System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
   bei System.ServiceModel.Channels.CommunicationObject.EndOpen(IAsyncResult result)

Exception rethrown at [0]: 
   bei Veeam.Engine.Wcf.PrimitiveServiceClient`1.Open(CancellationToken token)
   bei Veeam.Archiver.Integration.ArchiverConnector`2.CreateArchiverConnection(TE events, ICertificateValidator certificateValidator, IServiceConnectionConfig connectionConfig, Nullable`1 cancellationToken)
05.11.2020 17:41:26   31 (8008) Error: The server has rejected the client credentials.
05.11.2020 17:41:26   31 (8008) Type: System.ServiceModel.FaultException
05.11.2020 17:41:26   31 (8008) Stack:
05.11.2020 17:41:26   31 (8008) 
05.11.2020 17:41:26   31 (8008) Disconnecting from Veeam Backup for Office 365 server...
05.11.2020 17:41:26   31 (8008) Disconnecting from Veeam Backup for Office 365 server...

**Comment by nielsengelen** [comment]
This error comes from VBO itself and not the portal. I would advise to contact Veeam support for insight on what is causing this error.

**Comment by dominikmze** [comment]
Good Morning,

yes problem found. The tenant's name was case sensitive. After I typed it in correctly it worked.
