### ISSUE TITLE
Licensing-Tab does not show all Accounts used licenses of an organization

### ISSUE THREAD

**Issue by markusblogde** [nielsengelen/vbo365-rest#77]
Licensing-Tab does not show all Accounts used licenses of an organization.

1. Go to 'Licensing'
2. Click on 'View'
3. Scroll down to 'Bottom'
4. only 30 Accounts visible, but 89 Accounts licensed

**Comment by nielsengelen** [comment]
Hi, thanks for reporting. I'll see if this can be easily fixed by adjusting the defaults to a higher value and provide a "view all" option.

**Comment by nielsengelen** [comment]
I've just pushed a new commit (https://github.com/nielsengelen/vbo365-rest/commit/dbcd127badf85241b0451ef363fdff2087cf1445). This includes a quick solution to this normally. 

Can u download veeam.class.php and the files from the includes folder and replace them in your current installation. Afterwards let me know if it is resolved or not.

**Comment by markusblogde** [comment]
Hi Niels,

thank you for this quick work :-) 
The Problem is not fixed at all.
50 Accounts of 89 are visible now.

Markus

**Comment by nielsengelen** [comment]
Hi Markus, I was indeed a bit too fast. Can u try with the updated licensing file from commit https://github.com/nielsengelen/vbo365-rest/commit/920f35460c44b6c4b81bb89cd5fd4c6a3c656d09?

**Comment by markusblogde** [comment]
Hi Niels, very nice. Tried with new licensing.php and get all licensed Users! 
Thank you very much!
