### ISSUE TITLE
Restore entire folder

### ISSUE THREAD

**Issue by lasseoe** [nielsengelen/vbo365-rest#78]
Hi Niels,

It's currently not possible to restore entire folders - having to mark i.e. 10.000 emails will take ages and is error prone. 
Would it be possible to add a "Restore folder" button or checkbox?

**Comment by nielsengelen** [comment]
This is actually a good request and something I will add. Seems I never realized I didn't add this important feature. Will look into an easy way of adding it.

**Comment by nielsengelen** [comment]
This will be in v5 of the portal which is currently in progress. I hope to have it released/finished somewhere in January.

**Comment by nielsengelen** [comment]
Hi @lasseoe - this feature has been added with the v5 release.

Thanks for the request!
