### ISSUE TITLE
Repository: Object Storage Shows wrong Limit when used TB

### ISSUE THREAD

**Issue by markusblogde** [nielsengelen/vbo365-rest#79]
Limit is set at 10TB, look at available space but in Limit it is shown as GB:

![IMG_20201129_185427.jpg](https://user-images.githubusercontent.com/42450475/100549695-c9502500-3274-11eb-9670-7c9190e788fe.jpg)

**Comment by nielsengelen** [comment]
Could you let me know which s3 storage type this is in the backend?

**Comment by markusblogde** [comment]
Sure, it is Cloudian S3.

**Comment by nielsengelen** [comment]
Thanks, looks like for S3 the correct number is the one between brackets (10TB). The API returns the other number in GB hence why it states 10 GB. I'll have to do some more testing to see where the main issue resides and solve it.

**Comment by nielsengelen** [comment]
It looks like this is actually a bug within the VBO API. I've asked to verify this however it would be great if you could open a support case at Veeam and have this as an extra push for the solution. For now, I've hidden this field from the portal to not cause confusion.
