### ISSUE TITLE
after update to O365 backup v5 portal does not see any organizations

### ISSUE THREAD

**Issue by netscaper71** [nielsengelen/vbo365-rest#81]
Hello, after upgrade to v5 portal trough api does not see any organizations, please advise what to change.
![Screenshot_2](https://user-images.githubusercontent.com/19489733/101129916-2e0bd680-360b-11eb-84c7-3405ae0c8de7.png)
![Screenshot_1](https://user-images.githubusercontent.com/19489733/101129808-fe5cce80-360a-11eb-9eaf-33f9bd26f177.png)

**Comment by netscaper71** [comment]
All working fine after reboot the server where is placed portal (linux server, not Veeam itself).

**Comment by nielsengelen** [comment]
Hi, that was a quick fix :-). Normally, u can just change the version in the config file to /v5, perform a logout on the portal and log in again.

**Comment by markusblogde** [comment]
Hi, I had to disable and enable Rest-API on Veeam-Server after change config.php to v5.
