### ISSUE TITLE
Stop Team Restore

### ISSUE THREAD

**Issue by 0Backy0** [nielsengelen/vbo365-rest#85]
Hello,

First this portal is really cool !

**Describe the bug**
Since update V5 the restore from teams work, but when i stop sesion from portal O365 the console O365 no close the sesion restore

**To Reproduce**
1. Start restore in the portal
2. Stop the restore in the portal
3. Check O365 console

**Screenshots**
![image](https://user-images.githubusercontent.com/79275128/108395686-57093400-7216-11eb-9092-9240355814de.png)
![image](https://user-images.githubusercontent.com/79275128/108395716-5ec8d880-7216-11eb-8e47-509ae4f45e51.png)
![image](https://user-images.githubusercontent.com/79275128/108395732-625c5f80-7216-11eb-9aff-7fa1f67928b5.png)

**Comment by nielsengelen** [comment]
Hi, thanks for reporting this. I will look into this and report back if I found the issue and fix.

**Comment by nielsengelen** [comment]
I can't simulate this issue. Can you send me the RESTful API logs via mail (niels.engelen@veeam.com) which can be found under C:\ProgramData\Veeam\Backup365\Logs?

**Comment by 0Backy0** [comment]
Hello,

I send the mail with the log.
