### ISSUE TITLE
Alerts in the latest version of the portal, V5, are displaying html.

### ISSUE THREAD

**Issue by tar565** [nielsengelen/vbo365-rest#86]
**Describe the bug**
Alerts in the latest version of the portal, V5, are displaying html.

**To Reproduce**
1. Log into the portal.
2. Click on 'Exchange'
3. Select a restore date on the calendar that precedes the date of the first available restore point.
4. Click 'Start Restore'.
4. Error is displayed on confirming, clicking 'OK', the start of the restore session.

**Expected behavior**
An error alert which states that the chosen restore point date precedes the date of the first available restore point or similar.

**Screenshots**
[veeam_portal_error.txt](https://github.com/nielsengelen/vbo365-rest/files/6012070/veeam_portal_error.txt)
![veeam_portal_error](https://user-images.githubusercontent.com/774317/108544747-cfd3c300-72de-11eb-9cd3-5e420a7787e2.GIF)

**Desktop (please complete the following information):**
 - Windows 
 - Chrome (v88.0.4324.182)
 - Webserver XAMPP

**Additional context**

The attached text file, veeam_portal_error.txt, contains the full error message.

**Comment by nielsengelen** [comment]
I am unable to simulate this on the same setup. Are you logged in as an admin or tenant?

**Comment by tar565** [comment]
Morning Niels,

I've investigated the issue a little more this morning, and Xdebug appears to be the source of the issue, as opposed to the portal. On rolling back the Xdebug version, the alerts are as expected.
