### ISSUE TITLE
Invalid Credentials after upgrade to Veeam 11 hosted on the same server as o365 backup

### ISSUE THREAD

**Issue by eazy** [nielsengelen/vbo365-rest#87]
Hi,

not sure, maybe I missed something, but I we have Login issues since the update of another produkt on the same server.

Our Customers can't authenticate on the self service portal since we've updated veeam B&R from 10 to 11 which is running on the same maschine as Veeam o365 Backup. (classic auth, not MFA)

If've we are trying to login we get "Invalid credentials" and I can't see the login attempt in the Rest Log. 
We're using Api Version V5

Veeam 365 Backup was already running on latest version 5.

Any Ideas?

For now I will setup a new maschine to test whether the problem will exist there too or not.

Thanks

bye
  eazy

**Comment by nielsengelen** [comment]
I am not aware of any issues related to basic auth and VBR11/VBO together. If the issue persists, you may need to open a support case at Veeam to see if this could be a known issue.

**Comment by eazy** [comment]
Ok, thanks I'll do so and update that issue, maybe other selfportal Users have the same problem with the recommended setup.

**Comment by nielsengelen** [comment]
Ideally, both have their own dedicated servers as updates may interfere with components (usually unwanted). Hopefully, support can resolve the issue quickly.

**Comment by eazy** [comment]
Thats the way we're doing it with all our services, expect veeam. Step 1 in the docu https://helpcenter.veeam.com/docs/vbo365/guide/vbo_baas_sp.html?ver=50 describes to do it as we're running the setup at the moment.

But I were able to fix it by reinstalling o365 backup with the latest setup. Now everything is running fine. Hopefully nobody else will have that issue.

Thanks für your time!
