### ISSUE TITLE
Datepicker for backup restore not showing up

### ISSUE THREAD

**Issue by DominikZublasing** [nielsengelen/vbo365-rest#88]
**Description**
The datepicker on the page exchange seems to be not working.
The modal for the datepicker is not appearing when you are logged in as a customer.
The only way i am able to make it visible is when i enter the parameter "oid=<something>",
but then the date seems to be locked on january 1970.

**To Reproduce**
Sign in with a customer account 
Go to the exchangepage
click on the datepicker

**Screenshots**
![b1809776-2287-42ee-8a2d-67fa8dd562da](https://user-images.githubusercontent.com/80110135/110132205-37a00880-7dcb-11eb-86ad-647cb9aa78b0.jpg)

**Comment by nielsengelen** [comment]
Can you verify the explorers are installed correctly? It looks like there is an issue with the REST API in the background which causes this. Also, which VBO version are you running?

**Comment by DominikZublasing** [comment]
The Explorers should've been installed correctly and the REST API is working fine.
I am currently running the version 5.0.1.179.

**Comment by nielsengelen** [comment]
Can you check the RESTful API logs if there are any errors? Also, are you using basic or MFA auth?

**Comment by DominikZublasing** [comment]
I've looked into C:\ProgramData\Veeam\Backup365\Log\Veeam.Archiver.REST and found no error which would indicate such behaviour. I'm using basic and MFA-Login.
In addition to that i noted that the login via an admin account does not cause this misbehaviour

**Comment by DominikZublasing** [comment]
Is there already an update on this issue ?

**Comment by nielsengelen** [comment]
I'm unable to simulate this issue in my labs either. These dates are normally picked up via an API call and if something goes wrong, you should be able to see something in the RESTful API log.

Can you maybe enable browser debug console (F12 for firefox/chrome) and refresh the page when this happens? Does it return any error or warning there?

**Comment by DominikZublasing** [comment]
We finally were able to find the root of the problem.
The problem was that our Api returned a 500 error when calling one specific Route (GET /Organization)
causing the field oid never to be set which resulted in the missing/misbehaviour of the datepicker.

Sorry for the inconvenience and thank you all for the help!
