### ISSUE TITLE
Admin links not working

### ISSUE THREAD

**Issue by oneredherring** [nielsengelen/vbo365-rest#89]
Probably not a bug but something I've done wrong.
When logged in as admin I can access all restore tabs and functions and log out.
all of the other links (repositories, backup jobs, licenses) lead to a default IIS page with servername/# as the URL. 

Environment is IIS on Server 2019 with PHP 7.4, Chrome browser.

**Comment by nielsengelen** [comment]
Is this using the latest version of the portal? It may be related to the web.config file doing something wrong so I will have to verify this with the correct version.

**Comment by oneredherring** [comment]
I assume it's the latest version - I downloaded it with "git clone https://github.com/nielsengelen/vbo365-rest.git" four days ago.

**Comment by nielsengelen** [comment]
Can u try the following Web.Config file? Just make sure to remove the .txt extension.

[Web.Config.txt](https://github.com/nielsengelen/vbo365-rest/files/6155398/Web.Config.txt)

**Comment by oneredherring** [comment]
thanks - 

I downloaded the file, removed the .txt extension, renamed existing web.config, copied the new file into wwwroot, and ran iisreset.

But that did not improve things. The index page doesn't load at all now, just brings up the default IIS page. I can't even log in now. the exchange page will load briefly if I enter the direct URL but then it flicks back to the index / default IIS page.

**Comment by KelvinJones** [comment]
@oneredherring It almost sounds like "URL rewrite" is not installed?

**Comment by nielsengelen** [comment]
Please revert to the one from the project then. I will have to continue testing with what could cause the issue. I am not sure why the index rewrite fails but the others work fine for you.

**Comment by oneredherring** [comment]
yes, have reverted back.

URL rewrite is definitely installed, I can open the page and see the rules listed in IIS.

**Comment by oneredherring** [comment]
fixed it.

I found this link:
https://foonet.be/2021/01/29/veeam-backup-for-microsoft-office-365-self-service-web-portal-v5-release-with-teams-support/

and this important looking step that wasn't in your instructions here on github:

**Remove the iisstart.html and iisstart.png files from the folder.**

Once I did that it is working.

**Comment by nielsengelen** [comment]
Yes, that is my personal blog which I use to promote the project a bit :-). 

I'll improve the readme/instructions here on the next commit to clarify this. Glad you found the issue and thanks for sharing!
