### ISSUE TITLE
Restore - Error:

### ISSUE THREAD

**Issue by marmoe** [nielsengelen/vbo365-rest#9]
Hi Niels, 

I have installed the portal on a CentOS 7 server and things are looking good. However I'm not able to "Start Restore", all I get is an empty error message "Error:       ". This is when I'm logged on as a admin (local user from VBO server). When I log in as a tenant the portal is not showing me any restore points/backup jobs. I just see the date pull down menu and when I click "Start Restore", I get the same empty error message as from the admin session.

I have started investigation - checking logs etc. I cannot see anything pointing me in the right direction. This is what I see in the apache access log:

[20/Sep/2018:12:49:26 +0200] "GET /veeam.php?action=startexplorer&json=%7B%20%22explore%22%3A%20%7B%20%22datetime%22%3A%20%222018.09.17%2012%3A00%22%2C%20%22type%22%3A%20%22vesp%22%20%7D%20%7D&id=tenant HTTP/1.1" 200 519 "https://<portal>/sharepoint" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"

I have explorers on the VBO server and it all looks good there. I am able to start and disable backup jobs from the portal. Do you have any pointers on where to look here?

**Comment by nielsengelen** [comment]
The call looks ok, could you check the RESTful API service logs on the VBO service? These can be found under C:\ProgramData\Veeam\Backup365\Logs - called Veeam.Archiver.REST_...log

It looks like the REST call may fail and therefor the error you get in return is empty.

**Comment by marmoe** [comment]
Thank you. 
The REST log told me that "Validation failed. Certificate is not valid for host 127.0.0.1". It looks like I wasn't patient enough to wait for this when I checked the logs earlier. I remember the readme file mentioned the "no SSL verification", so I set verify to true for start and stop Explorer in veeam.classes.php

This gave me a "Restore session started" message and I can click OK - so we are getting closer. However, nothing happens and I'm sent back to the page where I can select organization.

I've tried to set verify to true on getMailbox/restoreMailbox and other explorer/restore relevant functions, but I get the same status. I cannot see anything in the REST log now complaining about certs (or anything for that matters).

**Comment by nielsengelen** [comment]
Did you install a valid SSL certificate on the VBO server? This can be configured under "General options" in the "REST API" tab. If you install a self-signed certificate and put the "verify" to false in the veeam.class.php file, it should work fine.

**Comment by marmoe** [comment]
Hi, 
There was something with the certificate. I reinstalled a self signed cert and restarted REST API service, and now it works :)
Thank you.
