### ISSUE TITLE
The web page is coming empty 

### ISSUE THREAD

**Issue by Ksvilen** [nielsengelen/vbo365-rest#93]
Hi There,

I installed the web interface on dedicated win2019 server in the same network with the O365 backup server and i am using admin account to connect.
The web page is coming empty and it is not discovering  / reading the environment.
I have configured REST API 4443 on the O365 Backup server and when I try with tenant's account it is coming just with the  email/one drive/SP - but again empty ...
Am I missing something ?

![image](https://user-images.githubusercontent.com/81445815/112695806-188d1780-8e5b-11eb-91b2-cb1492946eee.png)

![image](https://user-images.githubusercontent.com/81445815/112696639-9a317500-8e5c-11eb-9ee5-91a561a494c8.png)

**Comment by nielsengelen** [comment]
Which VBO version are you running?

**Comment by Ksvilen** [comment]
Hi Niels,
It is VBO 5.0.0.1070.
It is installed in with CCB10 10.0.1.1854 on the same servers

![image](https://user-images.githubusercontent.com/81445815/112851570-1a342680-9079-11eb-8aff-235c7259b43a.png)

**Comment by Ksvilen** [comment]
I saw a pending update for VBO to 5.0.1.179.
After the update, the VBO SS Portal is working!
Thanks for creating the Portal - this is great stuff and very helpful!

**Comment by nielsengelen** [comment]
Thanks for sharing. I will have to do a test with 5.0.0.170 to see if there is a difference.
