### ISSUE TITLE
Item Restore error

### ISSUE THREAD

**Issue by Kaveerp** [nielsengelen/vbo365-rest#95]
Hi nielsengelen

Please be advised that I am experiencing an issue with the Rest API.

The issue is when attempting to perform a restore, I receive the following the error attached, which is indicating "error creating resource message (with the server name - https://cld-vmconnect)"
![Restore error](https://user-images.githubusercontent.com/67784894/114512956-f4db1700-9c39-11eb-9699-e3f2bcdccce4.PNG)

**Expected behavior**
To perform a restore

**Screenshots**

**Desktop (please complete the following information):**
 -  OS: [Windows Server 2019] OS Build 17763.1852
  - Version [1809]
 -  Browser [chrome]

![Restore error](https://user-images.githubusercontent.com/67784894/114512681-a88fd700-9c39-11eb-9d69-ed6b477ef754.PNG)

**Comment by nielsengelen** [comment]
Do you get this with every SharePoint file? If you restart the restore session, is the issue still there?

**Comment by Kaveerp** [comment]
HI Nielsenglen,

I receive this on every sharepoint folder. I also noticed that when
restoring a folder which have large number of folders eg :

*Estimated total folders – 487   files – 17870 *the restore does not
perform a full restore, just restores some folders and files.

Kind regards

**Comment by nielsengelen** [comment]
On the full restore failing, this should be clear in the logs if something goes wrong (and may require Veeam support for assistance). 

Regarding the popup error, does this come up instantly or after a longer period of time?

**Comment by Kaveerp** [comment]
Hi  nielsengelen 

I will check the logs and advise Veeam Support.
Regarding the popup error, comes up instantly.

**Comment by Kaveerp** [comment]
Hi

Apologies, have not checked personal mail, This come up instantly.

Kind regards
