### ISSUE TITLE
cURL error 7: Failed to connect to 127.0.0.1 port 4443: connection refused

### ISSUE THREAD

**Issue by AntoninMich** [nielsengelen/vbo365-rest#96]
Hello everyone,
I just installed this on my IIS web server. I followed every steps (I think) and I have this issue when trying to connect with local credentials: 
cURL error 7: Failed to connect to 127.0.0.1 port 4443: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

I tried to replace 127.0.0.1 with the hostname but not working.

Thanks, 

Antonin

**Comment by nielsengelen** [comment]
Can u verify the RESTful API service is running? Is the portal running on the same server as VBO? Additionally, make sure there is no firewall blocking the connection.

**Comment by AntoninMich** [comment]
Portal running on the same server as VBO, firewall disabled and here is the result: 
![image](https://user-images.githubusercontent.com/17544792/115258449-4a7b5c00-a131-11eb-81c8-51290106e461.png)

**Comment by nielsengelen** [comment]
Can you use your browser on the server and see what happens if you browse to https://127.0.0.1:4443/swagger/ui? Do you get a result?
