### ISSUE TITLE
The provided credentials are incorrect

### ISSUE THREAD

**Issue by MatMathias** [nielsengelen/vbo365-rest#98]
Hi Nielsengelen,
Thank you for your work, it's great!
I managed to install the self-service portal but cannot connect.
As a windows administrator or with customer tenants.
Can you help me ?

**Comment by MatMathias** [comment]
I forgot to specify, the portal is installed on ubuntu server 20.

**Comment by nielsengelen** [comment]
Can u verify the RESTful API service is configured on the VBO server and there is no firewall issue? Are you seeing any error at all?

**Comment by MatMathias** [comment]
here is an nmap from the ubuntu server :

nmap 10.0.231.1 -Pn
Starting Nmap 7.80 ( https://nmap.org ) at 2021-05-05 16:08 UTC
Nmap scan report for 10.0.231.1
Host is up (0.00090s latency).
Not shown: 994 filtered ports
PORT     STATE  SERVICE
113/tcp  closed ident
135/tcp  open   msrpc
139/tcp  open   netbios-ssn
445/tcp  open   microsoft-ds
4443/tcp open   pharos
7070/tcp open   realserver

Enable REST service OK
![image](https://user-images.githubusercontent.com/83713142/117173738-5c196080-adcd-11eb-8679-1727ee86a44e.png)

Is there a log to determine the problem?

Thank you for your help.

**Comment by MatMathias** [comment]
Do I need to log in with the account registered for the organization?

I also enable tenants authentication :
![image](https://user-images.githubusercontent.com/83713142/117175246-eadaad00-adce-11eb-855d-e377b7c7b30a.png)

**Comment by nielsengelen** [comment]
You can either log in using the Windows administrator credentials (unless you blocked it via the config.php file) or using the account used for adding the organization.
